### ISSUE TITLE
Add a property to enable/disable

### ISSUE THREAD

**Issue by patricio-loduca-olx** [okta/okta-spring-boot#106]
Hi, I was looking a way to disable the authentication for local environments or integration test but I couldn't. Is there a way to disable it? Do you have in mind a feature to allow it?

Thanks!

**Comment by bdemers** [comment]
You can disable the autoconfig classes, something like:
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

If you are trying to do this for testing Spring has a few other options too

**Comment by bdemers** [comment]
What did you do to disable spring security?  Maybe we can trigger on that so you don't need to add `spring.security.oauth2.resourceserver.jwt.jwk-set-uri: false` ?

**Comment by patricio-loduca-olx** [comment]
Spring security is enabling really. But in base on a property, I'm configuring the security to allow any request or applying our security policies. The configuration to allow all request is:

```
@Configuration
@EnableWebSecurity
@ConditionalOnProperty(name = "spring.security.oauth2.resourceserver.jwt.jwk-set-uri", havingValue = "false")
public class PermissiveSecurityConfiguration extends WebSecurityConfigurerAdapter {

  @Override
  protected void configure(HttpSecurity http) throws Exception {
    http.authorizeRequests().anyRequest().permitAll().and().csrf().disable();
  }

}
```

I think it would be better to have a property `okta.oauth2.enable: false` to do that. And this property could be used in the conditional property of the class **OktaOAuth2ResourceServerAutoConfig** .

However, that's not enough. I wanted to remove the next properties of my **application-local.yaml**:

```
okta:
  oauth2:
    issuer: ***
    clientId: ***
    clientSecret: ***
```

If the property `spring.security.oauth2.resourceserver.jwt.jwk-set-uri: false` is not configured with that value (false) and those properties don't exist, there is another error in the class **OAuth2ResourceServerJwkConfiguration**. This is a consequence of the next source code, which is not able to create the bean because (I'm not sure) it needs the properties for the attribute **OAuth2ResourceServerProperties**. Maybe, the key is the mapper **OktaOAuth2PropertiesMappingEnvironmentPostProcessor**.

```
	@Bean
	@ConditionalOnProperty(name = "spring.security.oauth2.resourceserver.jwt.jwk-set-uri")
	@ConditionalOnMissingBean
	public JwtDecoder jwtDecoderByJwkKeySetUri() {
		return new NimbusJwtDecoderJwkSupport(this.properties.getJwt().getJwkSetUri());
	}
```

I hope you could understand my explanation.

**Comment by bdemers** [comment]
I think I understand, our goal is that if the corresponding okta.oauth2.* or equivalent spring properties are not set, then the Okta autoconfig classes should be disabled.  Would that work for you?

**Comment by patricio-loduca-olx** [comment]
Yes, that's looks good to me!

**Comment by EdSingleton** [comment]
This problem can be solved for integration tests by creating a WebSecurityConfigurerAdapter class along with your test classes.  The @Order annotation is necessary to ensure the test WebSecurityConfigurerAdapter has a higher priority than the production implementation.  The default order for WebSecurityConfigurerAdapter is 100, so any value less than 100 will work.

```
package com.somecompany.project;

import com.okta.spring.boot.oauth.Okta;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.PropertySource;
import org.springframework.core.annotation.Order;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.builders.WebSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;

@Configuration
@PropertySource("file:/etc/somecompany/settings/web-service.properties")
@EnableWebSecurity
@Order(10)
public class TestSecurityConfig extends WebSecurityConfigurerAdapter {
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
            .authorizeRequests().anyRequest().authenticated()
            .and()
            .oauth2ResourceServer().jwt();

        Okta.configureResourceServer401ResponseBody(http);
    }

    @Override
    public void configure(WebSecurity web) {
        web.ignoring().antMatchers("/**");
    }
}
```
