### ISSUE TITLE
Display actual username instead of sub

### ISSUE THREAD

**Issue by cniesen** [okta/okta-spring-boot#114]
The examples display `principal.getName()` and often label it incorrectly as the username ([example here](https://github.com/okta/okta-spring-boot/blob/e78d1855ece298da5a2955c3da46704d0ab2c336/examples/redirect-code-flow/src/main/java/com/okta/spring/example/controllers/WelcomeController.java#L34)). 
However, `principal.getName()` returns the sub (Subject Identifier).  While the sub for Access Token can be customized (by default it uses the Okta username e.g. email address) we get the ID Token which is always the clientID.  I guess that's part of the openid standard as answered in this [Q&A](https://devforum.okta.com/t/why-is-the-sub-claim-in-the-access-token-and-id-token-different/3978).

I assume most people desire the username not the internal clientID number when creating an application.

**Comment by bdemers** [comment]
Agreed! We will update that!

**Comment by mraible** [comment]
@bdemers If you change the default, will passing in `principle.getName()` still work with the Java SDK? For example, here's some code from a [blog post](https://developer.okta.com/blog/2018/01/23/replace-local-storage-with-okta-profile-attributes#create-a-holdingscontroller-to-communicate-with-oktas-api):

```java
package com.okta.developer.holdingsapi;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.okta.sdk.client.Client;
import com.okta.sdk.resource.user.User;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.bind.annotation.*;

import java.io.IOException;
import java.security.Principal;
import java.util.*;

@RestController
@RequestMapping("/api/holdings")
public class HoldingsController {
    private final Logger logger = LoggerFactory.getLogger(this.getClass());
    private final ObjectMapper mapper = new ObjectMapper();
    private final Client client;
    private final String HOLDINGS_ATTRIBUTE_NAME = "holdings";

    public HoldingsController(Client client) {
        this.client = client;
    }

    @GetMapping
    public List<Holding> getHoldings(Principal principal) {
        User user = client.getUser(principal.getName());

        String holdingsFromOkta = (String) user.getProfile().get(HOLDINGS_ATTRIBUTE_NAME);
        List<Holding> holdings = new LinkedList<>();

        if (holdingsFromOkta != null) {
            try {
                holdings = mapper.readValue(holdingsFromOkta, new TypeReference<List<Holding>>() {});
            } catch (IOException io) {
                logger.error("Error marshalling Okta custom data: " + io.getMessage());
                io.printStackTrace();
            }
        }

        return holdings;
    }

    @PostMapping
    public Holding[] saveHoldings(@RequestBody Holding[] holdings, Principal principal) {
        User user = client.getUser(principal.getName());
        try {
            String json = mapper.writeValueAsString(holdings);
            user.getProfile().put(HOLDINGS_ATTRIBUTE_NAME, json);
            user.update();
        } catch (JsonProcessingException e) {
            logger.error("Error saving Okta custom data: " + e.getMessage());
            e.printStackTrace();
        }
        return holdings;
    }
}
```

**Comment by bdemers** [comment]
Yup! `client.getUser()` will work with both email address and the id.

**Comment by arvindkrishnakumar-okta** [comment]
This issue is no longer applicable, I believe. Please feel free to reopen if I am wrong.
