### ISSUE TITLE
Customizing UserUtil

### ISSUE THREAD

**Issue by cniesen** [okta/okta-spring-boot#117]
The okta-spring-boot library is nearly perfect for my use at work.  The only things are:

1) We'd want the username instead of the clientID in the name (related to issue #114).

2) We'd only want the Okta assigned groups and not the default ROLE_USER  and SCOPE_ groups.  (Any reason why these would still be desired?)

I was able to nicely change the okta-spring-boot libary by overriding the UserUtil class, but it seems kind of an hackish way to do that.
https://github.com/cniesen/okta-springboot-example/blob/custom-userutil/src/main/java/com/okta/spring/boot/oauth/UserUtil.java
So my questions are:

1) Although hackish is this acceptable?

2) Do other users have a similar needs and would it make sense to expose these customization properly in the okta-spring-boot libary?

Thanks,

  Claus

**Comment by bdemers** [comment]
You should be able to pull those details from the User attributes, something like:
https://github.com/okta/samples-java-spring/blob/master/okta-hosted-login/src/main/java/com/okta/spring/example/CodeFlowExampleApplication.java#L62-L64

If you have already tried that can you explain how you are using the user/auth object, maybe that will help us expose something better if needed.

**Comment by cniesen** [comment]
Pretty much as in my [sample app](https://github.com/cniesen/okta-springboot-example/tree/custom-userutil) linked above.
 - To access the Okta username: `principal.getName()`
 - For role/group permissions either
  `@PreAuthorize("hasAuthority('Admin)")` in the controller or
  `.antMatchers("/admin").hasAuthority('Admin')` in WebSecurityConfigurerAdapter 

I guess the extra roles in authority list aren't that big of an issue but having the ability to use `principal.getName()` instead of `((OAuth2AuthenticationToken) principal).getPrincipal().getAttributes().get("preferred_username")` would be quite nice.

**Comment by bdemers** [comment]
You should be able to simplify getting the principal by injecting the OidcUser direction by using the following annotation: `@AuthenticationPrincipal OidcUser user`

For example:
```java
    @GetMapping("/")
    String home(@AuthenticationPrincipal OidcUser user) {
        return "Hello " + user.getAttributes().get("preferred_username");
    }
```

**Disclaimer:** the above is cobbled together from a few different sets of notes, but give that a shot and let me know.

**Comment by cniesen** [comment]
Your code snipped works flawless.  I guess that works for me.  Thanks @bdemers for your help, time and the great library.
