### ISSUE TITLE
No unauthorized error when setting up a resource error

### ISSUE THREAD

**Issue by mraible** [okta/okta-spring-boot#119]
With v0.6.1 of this starter, if you set up a resource server and configured your Okta settings in `application.properties`, you'd get an "unauthorized" error when you tried to hit http://localhost:8080.

From https://developer.okta.com/blog/2018/12/03/bootiful-spring-boot-java-vue-typescript#create-an-oidc-app-in-okta:

![image](https://user-images.githubusercontent.com/17892/53699025-2ddd0800-3da1-11e9-833a-d9ed78c5fe8c.png)

With v1.1.0, when you set up a resource server with the following code:

```java
@Configuration
static class OktaOAuth2WebSecurityConfigurerAdapter extends WebSecurityConfigurerAdapter {
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        // @formatter:off
        http
            .authorizeRequests().anyRequest().authenticated()
            .and()
            .oauth2ResourceServer().jwt();
        // @formatter:on
    }
}
```

It redirects to Okta for auth, then displays the following error.

<img width="954" alt="screen shot 2019-03-03 at 10 45 05 am" src="https://user-images.githubusercontent.com/17892/53699044-6d0b5900-3da1-11e9-895b-20643c8d8cb4.png">

The previous behavior seems more appropriate.

**Comment by mraible** [comment]
I'm reopening this issue because I think it can be improved. The error in the 1.x version of our starter looks as follows:

![image](https://user-images.githubusercontent.com/17892/57574698-1bafc380-73fb-11e9-9e01-fb1d5f18e887.png)

When using 1.2.0, there is no error in Firefox. You just get a blank screen.

![Screen Shot 2019-05-11 at 2 44 33 PM](https://user-images.githubusercontent.com/17892/57574717-51ed4300-73fb-11e9-820c-145442f4755e.png)

In Chrome, it shows you the 401, but the "This page isn't working" looks kinda funny.

<img width="957" alt="Screen Shot 2019-05-11 at 2 44 16 PM" src="https://user-images.githubusercontent.com/17892/57574721-5fa2c880-73fb-11e9-98b4-0020e15ad2ed.png">

**Comment by bdemers** [comment]
A little late responding to this, but I had updated the sample app with details on how to configure the browser-friendly response:

https://github.com/okta/samples-java-spring/blob/master/resource-server/src/main/java/com/okta/spring/example/ResourceServerExampleApplication.java#L42-L43
