### ISSUE TITLE
Document what okta-spring-boot-starter does

### ISSUE THREAD

**Issue by sanitas2** [okta/okta-spring-boot#122]
The actual documentation doesn't really tell much about it. I was under an impressions it's some internal library, I was quite surprised that it exposes some endpoints. Like /login or /logout. Logout seems to accept some POST request to logout as well. Those things are not mentioned around here. Also I think those things should be somehow configurable (like I followed a tutorial and for login I have /custom-login endpoint, I don't want to have /login as well). Also sometimes an error page appears which doesn't look very nice, it would have been nice to have documentation saying how to style it. I think those things are quite obvious things to write down, so maybe I am just missing a link to documentation?

**Comment by bdemers** [comment]
@sanitas2 this lib just helps configure Spring Security OAuth/OIDC (as well as adds a little sugar for Okta users, like improved access token validation, and adds support for Okta custom claims to Spring Security authorities)

I'll take a shot at making this more clear in our README though.

As for your questions about how /login /logout works the best resource would be the Spring Security documentation, but this [Baeldung post](https://www.baeldung.com/spring-security-logout) looks like it may answer your questions too.

If you get stuck reach out to us!
