### ISSUE TITLE
Spring Boot Starter - Refresh Tokens

### ISSUE THREAD

**Issue by sunilkosuri** [okta/okta-spring-boot#133]
Hi,

I am new to Okta/OIDC and just implemented the OIDC Authorization Code Flow using your Spring Boot 1.2.1 starter (Angular 6 is the client I am using).  Everything works well.

Using the information in the OAuth2AuthenticationToken, I am creating my own JWT Token that contains the 

**subject** (getPrincipal().getAttributes().get("preferred_username")), 
**authorities** (getPrincipal().getAttributes().get("groups")), 
and an **expiration** (1 day).

I am wondering whether or not I should be doing anything else related to refresh tokens when using OIDC and your starter. If I do, how do I work with refresh tokens using the Okta Spring Boot Starter?

Thank you.

Sunil

**Comment by bdemers** [comment]
Hey @sunilkosuri!

I'm not sure I fully understand your question.  You mentioned that you are using an Auth Code Flow and an Angular 6 client. Is your client hosted by your Spring Boot App?  If so then from the client perspective it would just be a typical servlet session?

You are creating your own JWT token? How are you doing this? It sounds like there is a little overlap between what Spring Security is doing and what your application is doing?

**Comment by sunilkosuri** [comment]
Maybe I am confused.  Is there any article that explains how to implement the "authorization code" flow for an Angular SPA front-end calling a Spring Boot back-end using a ReST API?  The articles I found were using an implicit flow.

**Comment by bdemers** [comment]
We will have examples soon using an Auth Code Flow with PKCE see okta/okta-oidc-js#348
(or you could use any other standard oauth client)

On the Spring Side (which would be a Resource Server in your case), is basically just validating a token, any management of that token would happen in the client that obtained the original token.

Does that help?

**Comment by mraible** [comment]
@sunilkosuri Check out JHipster. It generates a Spring Boot backend with Auth flow code configured. The front end is Angular (by default). Here’s a blog post I wrote about it recently: https://developer.okta.com/blog/2019/04/04/java-11-java-12-jhipster-oidc.
