### ISSUE TITLE
Separating OAuth2 issuer and jwk uri in resource server

### ISSUE THREAD

**Issue by ayushsagar** [okta/okta-spring-boot#134]
In my resource server the access token I receive in production environment has issuer set to something like `https://myorg.okta.com`. And if I set `okta.oauth2.issuer` property to this I get `java.lang.IllegalStateException: Could not obtain the keys` when I try to validate token.

The actual jwk uri is something like `https://myorg.okta.com/oauth2/v1/keys` so if I set `okta.oauth2.issuer` property to `https://myorg.okta.com/oauth2` it fixes that issue. However, it now fails token validation because this issuer does not match issuer id in the token which is `https://myorg.okta.com`

It seems to me that this is appending `/v1/keys` internally to given `okta.oauth2.issuer` value which works in demo environment but not in my production environment. So I need to be able to separate the issuer it expects in the token vs the uri for jwk.

**Comment by mraible** [comment]
@ayushsagar The default authorization server is at `https://myorg.okta.com/oauth2/default`. Can you try that and see if it fixes the problem?

**Comment by ayushsagar** [comment]
So it turns out the issue is not what I thought. The kid (key id) of access token didn't match the keys here `https://myorg.okta.com/oauth2/v1/keys` and that was the real issue.

On reading this docs here <https://developer.okta.com/docs/concepts/auth-overview/#authorization-servers> I learn that unless I specify an authorization server, like `default` as @mraible mentions, I'm using the Okta internal auth server which is not meant to be used by user applications.

And on reading through this thread <https://devforum.okta.com/t/error-the-signature-key-was-not-found/696> I find that we need to buy API Access Management feature to get that working which is prohibitively expensive with our user count.

So my workaround is to move away from this resource server to hitting the endpoint `https://myorg.okta.com/oauth2/v1/userinfo` with access token.

**Comment by nbarbettini** [comment]
@ayushsagar Sorry about the confusion. We're working on making this clearer.

For context, who are the users of your resource server? (if you don't mind sharing)
I'm trying to get a better sense of what applications people are building when they run into this issue.

**Comment by kushan2** [comment]
> 
> 
> So it turns out the issue is not what I thought. The kid (key id) of access token didn't match the keys here `https://myorg.okta.com/oauth2/v1/keys` and that was the real issue.
> 
> On reading this docs here https://developer.okta.com/docs/concepts/auth-overview/#authorization-servers I learn that unless I specify an authorization server, like `default` as @mraible mentions, I'm using the Okta internal auth server which is not meant to be used by user applications.
> 
> And on reading through this thread https://devforum.okta.com/t/error-the-signature-key-was-not-found/696 I find that we need to buy API Access Management feature to get that working which is prohibitively expensive with our user count.
> 
> So my workaround is to move away from this resource server to hitting the endpoint `https://myorg.okta.com/oauth2/v1/userinfo` with access token.

if its a 'kid' not matching issue, "kid" in JWT token header(metadata) section, should match with "https://myorg.okta.com/oauth2/v1/keys" on of the "kid" to navigate the correct key.
