### ISSUE TITLE
Access Denied Error while authorizing

### ISSUE THREAD

**Issue by anuraram12345** [okta/okta-spring-boot#135]
I have below Security

@SpringBootApplication
@EnableSwagger2
@EnableMongoRepositories
@EnableWebSecurity(debug = true)
@Component
//@EnableResourceServer
@EnableGlobalMethodSecurity(prePostEnabled = true)
//@EnableResourceServer
//@EnableAutoConfiguration(exclude = OAuth2AutoConfiguration.class,
 //                                  // SecurityAutoConfiguration.class, SecurityFilterAutoConfiguration.class)
public class NotificationConfigApplication {

    public static void main(String[] args) {
        SpringApplication.run(NotificationConfigApplication.class, args);
    }

    @Bean
    public RestTemplate restTemplate(RestTemplateBuilder builder) {
        return builder.build();
    }
    

    @Configuration
    static class OktaOAuth2WebSecurityConfigurerAdapter extends WebSecurityConfigurerAdapter {

        @Override
        protected void configure(HttpSecurity http) throws Exception {
        	 http.authorizeRequests()
             // Require authentication for all requests under /api/private
             .antMatchers("/notificationconfig/v2/**").authenticated()
         .and()
             .oauth2ResourceServer().jwt();
        	 
        }
    }
    
   
    @Bean
    public FilterRegistrationBean<CorsFilter> simpleCorsFilter() {
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        CorsConfiguration config = new CorsConfiguration();
        config.setAllowCredentials(true);
        config.setAllowedOrigins(Arrays.asList("http://localhost:3000","http://localhost:3001"));
        config.setAllowedMethods(Collections.singletonList("*"));
        config.setAllowedHeaders(Collections.singletonList("*"));
        source.registerCorsConfiguration("/**", config);
        FilterRegistrationBean<CorsFilter> bean = new FilterRegistrationBean<>(new CorsFilter(source));
        bean.setOrder(Ordered.HIGHEST_PRECEDENCE);
        return bean;
    }

}

spring:
  security:
    basic:
      enabled: false
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://t-mobile.oktapreview.com/oauth2/ausfpzqyl4GgxOyBf0h7
      okta:
       oauth2:
         issuer: https://t-mobile.oktapreview.com/oauth2/ausfpzqyl4GgxOyBf0h7
         clientId: 0oafjhne8rRb0bNd80h7   
         scope: 'openid profile email'

I send 'Authorization <token> in header got localhost:8080/

I get Access Invalid CORS request

In the Spring boot server logs i see

[13 Jul 2019 03:21:17] [DEBUG] [] [ExceptionTranslationFilter handleSpringSecurityException]:[181 ] - Access is denied (user is anonymous); redirecting to authentication entry point
org.springframework.security.access.AccessDeniedException: Access is denied

**Comment by bdemers** [comment]
Hey @anuraram12345!

CORS is always a fun one ;)

I've found the easiest way to configure it looks something like this:
https://github.com/okta/samples-java-spring/blob/master/resource-server/src/main/java/com/okta/spring/example/ResourceServerExampleApplication.java#L40-L49
Or: https://developer.okta.com/docs/guides/protect-your-api/springboot/configure-cors/

We have a few posts on the topic too: https://developer.okta.com/blog/2019/05/22/java-microservices-spring-boot-spring-cloud.

The Spring Security guide: https://docs.spring.io/spring-security/site/docs/current/reference/html/web-app-security.html#cors

It sounds like you might just need to tweak your `setAllowedOrigins`?
