### ISSUE TITLE
/logout does not kill the Okta Auth session

### ISSUE THREAD

**Issue by vekdeq** [okta/okta-spring-boot#139]
Hi Team, 

Raising this known issue in this forum as instructed in other forum. The /logout is not killing okta session when upgraded to Spring Security 5.2.0.M4 - using okta spring boot starter. From network logs, I could see the <app>/logout hit from app UI link - which redirect to app/login page (default settings) - but doesn't kill Okta session (my apps IDP). This was known issue - but was expected to be fixed with Spring Security 5.2.0.M4 - but still not fixed. 

 I have raised this in Spring Security forum too -  awaiting response. 

Vivek

**Comment by bdemers** [comment]
What does your logoutSuccessHandler (and other HttpSecurity config look like?)
I messed with this a while back `M2` IIRC, and this is what I used at the time: https://github.com/okta/okta-spring-boot/compare/oidc-logout?expand=1

(we cannot merge it until 5.2 goes GA, but you should be able to do something similar in your app)

NOTE: by default logging out of your Spring Security session does NOT kill any remote sessions, this is expected, and in many applications is the desired effect.
RP initiated Logout is currently being tracked under: #126

Closing as duplicate to #126
