### ISSUE TITLE
Please confirm compatibility with Spring Boot 2.2

### ISSUE THREAD

**Issue by snicoll** [okta/okta-spring-boot#140]
We're heading towards an RC1 of Spring Boot 2.2 soon, followed [by GA in Q4](https://github.com/spring-projects/spring-boot/milestones). Can you please confirm full compatibility of the starter with Spring Boot 2.2?

As soon as we hear from you, we can enable the starter again on start.spring.io, see https://github.com/spring-io/start.spring.io/issues/266

Thanks!

**Comment by bdemers** [comment]
@snicoll confirmed
I bumped the version of Spring Boot to 2.2.0.M6, and all of our integration tests pass.

Is there a more proactive [read: automated] way we can confirm compatibility between versions?
CI? some sort of trigger?

**Comment by snicoll** [comment]
@bdemers sweet, thanks for the quick reply. Two things:

* A CI where you override the [Spring Boot version](https://github.com/okta/okta-spring-boot/blob/f5d230c8c05dd619f28388cab4118e546998b45d/pom.xml#L34) to the upcoming release is very much appreciated. If you do this, we won't disable the entry as we did here.
* Regular updates to the starter is appreciated as it provide the latest and greatest on both sides: compatibility with Spring Boot and related components such as Spring Security and Okta version. I guess we can expect a `1.3.0` at some point?

If you specify somewhere in your README the Spring Boot generations you're testing against, I should be able to spot that and react accordingly. 

I am going to enable Okta again but we could reuse this issue to setup CI or whatever you'd like to do. Thanks!

**Comment by bdemers** [comment]
Thanks @snicoll!
That should be easy enough!

We are excited for the next release (lots of great OAuth related updates in there!), and have a backlog that is patiently waiting :D

**Comment by snicoll** [comment]
> have a backlog that is patiently waiting :D

I am curious what you mean by that. Waiting for what exactly?

**Comment by bdemers** [comment]
We can use this issue to track it, if you prefer. 

Waiting for the release, to start taking advantage of the new features. (RP-initiated logout, PKCE support, opaque tokens, etc)
(Initial testing of with these features has gone well)

**Comment by snicoll** [comment]
@bdemers any news about that stuff? I'd like to make sure users can use Okta with SB 2.2

**Comment by bdemers** [comment]
@snicoll I can confirm compatibility with 2.2.0.M6.  The only remaining task is to set up a test harness to automate the testing of future versions (possibly just the ITs).

How are the versions for start.spring.io resolved? I see a couple of options to get the _latest_ version,  
- Maven version ranges - less accurate, possibly false positives with any intermittent builds
- http request to start.spring.io - current list of versions, but this would be _after the fact_
- triggered manually by watching release notices - manual...

Have any recommendations? What are other folks doing?

**Comment by snicoll** [comment]
@bdemers sorry for the late reply. I've restored compatibility with SB 2.2+ and I trust you'll setup something in place for future feature release. 

Versions of start.spring.io are resolved via a call to https://spring.io/project_metadata/spring-boot

I don't have a general recommendation. My personal preference would be to follow things up and act accordingly. We usually have a new feature release every year so there's plenty of opportunity when working on this project to adapt CI infrastructure if necessary IMO. I also expect releases of this very starter matching up-to-date version of Spring Boot (and the dependencies it manages) which is yet another opportunity to check if the feature release we're working on still works with your use cases.

If there is something we can do on our side to make this easier, feel free to let us know.

**Comment by bdemers** [comment]
Thanks @snicoll!

**Comment by joshlong** [comment]
I created a Spring Boot 2.2.0.RC1 app with Kotlin and Okta tonight and it fails to start.

```
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.okta.spring.boot.oauth.ReactiveOktaOAuth2ResourceServerHttpServerAutoConfig$OktaOAuth2ResourceServerBeanPostProcessor.postProcessAfterInitialization(ReactiveOktaOAuth2ResourceServerHttpServerAutoConfig.java:60)

The following method did not exist:

    'void org.springframework.security.oauth2.server.resource.authentication.ReactiveJwtAuthenticationConverterAdapter.<init>(org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationConverter)'

The method's class, org.springframework.security.oauth2.server.resource.authentication.ReactiveJwtAuthenticationConverterAdapter, is available from the following locations:

    jar:file:/Users/jlong/.m2/repository/org/springframework/security/spring-security-oauth2-resource-server/5.2.0.RELEASE/spring-security-oauth2-resource-server-5.2.0.RELEASE.jar!/org/springframework/security/oauth2/server/resource/authentication/ReactiveJwtAuthenticationConverterAdapter.class

It was loaded from the following location:

    file:/Users/jlong/.m2/repository/org/springframework/security/spring-security-oauth2-resource-server/5.2.0.RELEASE/spring-security-oauth2-resource-server-5.2.0.RELEASE.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of org.springframework.security.oauth2.server.resource.authentication.ReactiveJwtAuthenticationConverterAdapter
```

Any idea how to fix @bdemers? We'd like to use Spring Boot 2.2.0.RC1 in our demo tomorrow at SpringOne.

**Comment by bdemers** [comment]
Doh!

I'll take a look right now

**Comment by snicoll** [comment]
Let me know if I can help

**Comment by joshlong** [comment]
I was able to fix this by excluding the resource server as a dependency.

```xml
<dependency>
    <groupId>com.okta.spring</groupId>
    <artifactId>okta-spring-boot-starter</artifactId>
    <version>1.2.1</version>
    <exclusions>
        <exclusion>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-oauth2-resource-server</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

BTW, this is @mraible on @joshlong's computer. ;)

**Comment by bdemers** [comment]
If you have a sec, can you get me a `mvn dependency:tree` ?

**Comment by bdemers** [comment]
Snippet from japicmp, comparing: org.springframework.security:spring-security-oauth2-resource-server:5.1.6.RELEASE and 5.2.0.RELEASE

![image](https://user-images.githubusercontent.com/99954/66539439-799d2000-eaed-11e9-8c0d-834b6a2e44c0.png)
From: https://github.com/spring-projects/spring-security/commit/3cb09758602484629b06da3c67257c60692d9bb5#diff-ca6c3586180e2510a1de9d7cb0d041ae

**NOTE:** the `!` means a breaking binary change.

This IS source compatible (which is why it passed my tests), but fails with start.spring.io
cc: @jzheaux 

At first glance, this change looked fine to me but I think I need to brush up on the nuances of binary compabiilty.

**Comment by bdemers** [comment]
I guess I was thinking about source compatible changes instead of binary-compatible changes: https://wiki.eclipse.org/Evolving_Java-based_APIs_2#Evolving_API_classes_-_API_methods_and_constructors

**Comment by bdemers** [comment]
@snicoll is it possible to configure a different version of okta-spring-boot-starter with the various versions of Boot: one for 2.1.9, and another with 2.2.x ?

**Comment by snicoll** [comment]
Yes.
