### ISSUE TITLE
error running hosted-login-code-flow: signUpAppId of undefined

### ISSUE THREAD

**Issue by saiyelurimhe** [okta/okta-spring-boot#141]
I am trying to run the example hosted-login-code-flow and I see the following error after I Sign-in

`Uncaught TypeError: Cannot read property 'signUpAppId' of undefined`

Application configuration is proper, I can see the `/api/v1/authn` call return 200

**Comment by bdemers** [comment]
Take a look at this one, it’s a more standalone version of this example
https://github.com/okta/samples-java-spring/tree/master/custom-login

I will through out recommendation to use the Okta Hosted option if/when possible.  It is MUCH less work and will be easier to maintain. You can still customize the login page (and and a custom domain) though your Okta admin dashboard.

**Comment by saiyelurimhe** [comment]
This is great, Thank You @bdemers
