### ISSUE TITLE
How to handle two issuers

### ISSUE THREAD

**Issue by dongmei-cao** [okta/okta-spring-boot#149]
Per instruction, I need to specify `okta.oauth2.issuer`.  But my resource server needs to allow access_tokens issued from two different authorization servers that I have added in my Okta Org. How do I use this okta-spring-boot starter with two `issuers`

Thanks!

**Comment by bdemers** [comment]
You may want to use Spring-Security directly.  Support for this was [recently added](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#servlet) in Spring Security 5.2 (Spring Boot 2.2)

Depending on what you are doing, you might be able to use a single Authorisation Server with multiple policies too.

**Comment by arvindkrishnakumar-okta** [comment]
Feel free to reopen if further discussion is still needed.
