### ISSUE TITLE
Override User Details Service

### ISSUE THREAD

**Issue by dcods22** [okta/okta-spring-boot#150]
Im looking to override the user details service, our use case is that once a user has logged in we want to add roles from a DB. in other security implementations we override a bean extending a class such as SAMLUserDetailsService and then can catch the user before it goes into SecurityContextHolder so we can access it later.  It looks like you currently create a new instance of the object were looking to override by my guessing

https://github.com/okta/okta-spring-boot/blob/ab7a09cf696c444b50e33cb2080db86d73e6df27/oauth2/src/main/java/com/okta/spring/boot/oauth/OktaOAuth2Configurer.java#L89

Im not sure how to handle this but this is a major blocker for us since we do not want to only have the groups returned from a user we were advised by OKTA to maintain roles in our DB

**Comment by bdemers** [comment]
Hey @dcods22! Take a quick look at #146, do you think that would work for you? (if not, please post on that issue and let us know!)

Duplicates: #136 
Fixed by: #146

**Comment by dcods22** [comment]
Yes that would work for the roles but ideally we would want to add more to the user in the SecurityContextHolder such as specific user details for that specific app that is not held in Okta. This is done in all other authorization implementations I’ve implemented. SAML, LDAP etc. The flexibility of being able to extend that service somehow would be ideal so we can do whatever we need to with the user before it goes into spring security
