### ISSUE TITLE
Cannot inject scopes into a primitive array or list

### ISSUE THREAD

**Issue by tai1nguyen** [okta/okta-spring-boot#153]
First time posting an issue, please be gentle with me.

I have a spring boot project set up with "spring-boot-starter" v2.2.2 and "okta-spring-boot-starter" v1.3.0

Currently attempting to inject the scopes property into a configuration class but am unable to resolve the placeholder. Looking at how these variables are being resolved I can see that the values for the scopes array are being mapped to "okta.oauth2.scopes[0]" and "okta.oauth2.scopes[1]" but the key that is being matched on is "okta.oauth2.scopes".

application.yml
```
spring:
    profiles: local
okta:
    oauth2:
        scopes: ['openid', 'profile' ]
        issuer : https://test.com/oauth2/default
        audience: test
        client-id: clientId
        client-secret: clientSecret
```

OAuthConfig.java
```
@Configuration
public class OAuthConfig extends WebSecurityConfigurerAdapter {

    @Value("${okta.oauth2.client-id}")
    private String clientId;

    @Value("${okta.oauth2.client-secret}")
    private String clientSecret;

    @Value("${okta.oauth2.scopes}")
    private String[] scopes;

    @Value("${okta.oauth2.issuer}")
    private String issuer;

}
```

Error
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'OAuthConfig': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'okta.oauth2.scopes' in value "${okta.oauth2.scopes}"
```

[Here](https://github.com/okta/okta-spring-boot/files/4061507/propertyInjectionDefect.zip) is the project zip in case anyone wants to try reproducing it.

**Comment by bdemers** [comment]
@tai1nguyen try something like:

```yaml
okta:
  oauth2:
    scopes:
    - profile
    - openid
```

something like this should work too: `-Dokta.oauth2.scopes=profile,openid`

Let us know how it goes!

Though, I would have guessed your example would have worked too

**Comment by tai1nguyen** [comment]
@bdemers So I looked into it a bit more and this seems to be a quirk with how spring consumes/reads arrays in yaml. I tried you first suggestion and it did not work, however setting it as an environment variable did work. I've also found that if you wrote your array like below it would also work.

application.yml:
```
okta:
    oauth2:
        scopes: profile, openid
```

Thanks for the swift response!

**Comment by bdemers** [comment]
Thanks for following up !
