### ISSUE TITLE
groups not mapped in Granted Authorities: []

### ISSUE THREAD

**Issue by swagatdishri** [okta/okta-spring-boot#157]
in version okta-spring-boot-starter 2.2.1 groups are mapped to **Granted Authorities: []** but in version 1.3.0 groups are not mapped.
 when i am testing using hasAnyAuthority() getting unauthorized.

how to check the authority in new version,

Thanks

**Comment by bdemers** [comment]
@swagatdishri thanks for the report, this will be fixed in the next release (due out any day now)

My guess is you can work around this in the current version by setting:
```properties
spring.security.oauth2.client.registration.okta.client-name = Okta
```

Going forward we are using the registration id instead of the client name (and we have included a test for this)
