### ISSUE TITLE
How to extract claim from Jwt

### ISSUE THREAD

**Issue by ilamathyIlangovan** [okta/okta-spring-boot#158]
Hi Team,

I am using okta spring boot starter in my application. I want to extract a value (userId) from payload(claim) and cache the token with expiry time so that for subsequent request from the same user, jwtToken validation can be skipped. 

               ` .addFilterBefore(new JwtRequestFilter(), UsernamePasswordAuthenticationFilter.class)
                  .oauth2ResourceServer().jwt();`

Could you please help me with some example on how this can be achieved in Filters? Thanks in advance!

**Comment by bdemers** [comment]
Hey @ilamathyIlangovan!
Can you explain what you are attempting to do in more detail?  Spring Security provides much of this out of the box.

**Comment by ilamathyIlangovan** [comment]
Hi @bdemers ,
I am planning to cache jwtToken with userId as key(with expiry time) after successful validation.
Whenever a new request comes from the same user, userId which is part of claims should be extracted from jwtToken and verify wether it exists in the cache. If it exists in cache, .oauth2ResourceServer().jwt() should be skipped.

                 http
                .authorizeRequests().anyRequest().authenticated()
                .and()
                 .addFilterBefore(new JwtRequestFilter(), UsernamePasswordAuthenticationFilter.class)
                .oauth2ResourceServer().jwt();

I want to know how to extract claims from jwtToken in the Filters. Do you have similar example on caching jwtToken?

**Comment by bdemers** [comment]
@ilamathyIlangovan I'm sorry, I'm still not following what you are asking.
What you are describing is very similar to how Spring Security works out of the box.

Why are you trying to skip the JWT validation? Are you just trying to avoid the cost of validating the JWT?  If so I'd recommend against that.  the `jwt()` operation is local, and it would already be faster than using `opaque()` (which requires a remote HTTP call).  If you want to skip the JWT validation all together you could use a session cookie.

What are your concerns that you are trying to work around?

**Comment by ilamathyIlangovan** [comment]
Thanks @bdemers. I was not aware that jwt() is operation is local.
Could you please elaborate on session cookie part? 
If possible please share an example. Thanks in advance.

**Comment by bdemers** [comment]
Ahhhh!
In that case, you _shouldn't_ need to worry about cookies for a resource server, just use the header `Authorization: Bearer <access token>`.

The JWT will be validated locally (and the public key used for validation will be cashed).

It sounds like the default behavior is what you are looking for?

**Comment by ilamathyIlangovan** [comment]
yes @bdemers . Thats what I was looking for :)
Thanks a lot for the clarification.
