### ISSUE TITLE
 An error occurred while attempting to decode the Jwt: The ID Token contains invalid claims: {iat=2020-03-18T18:31:58Z}

### ISSUE THREAD

**Issue by Rajasekharjava** [okta/okta-spring-boot#165]
Okta Blocker Analasys:
-----------------------

We developed sample application with spring boot below version. It's not working the code from March first week.

SpringBoot version 2.1.4 /later versions Spring 5.X + Okta spring boot starter 1.0.0, 1.2.0, 1.3.0

Referece: https://developer.okta.com/blog/2019/05/15/spring-boot-login-options

Failed reference log:

```txt
23:59:54.550 [qtp1223357487-28] DEBUG org.springframework.web.client.RestTemplate - HTTP POST https://**.oktapreview.com/oauth2/default/v1/token
23:59:54.553 [qtp1223357487-28] DEBUG org.springframework.web.client.RestTemplate - Accept=[application/json, application/*+json]
23:59:54.557 [qtp1223357487-28] DEBUG org.springframework.web.client.RestTemplate - Writing [{grant_type=[authorization_code], code=[wzOVlKFV6bLvOdi2P54f], redirect_uri=[http://localhost:4321/login/oauth2/code/okta]}] as "application/x-www-form-urlencoded;charset=UTF-8"
23:59:55.788 [qtp1223357487-28] DEBUG org.springframework.web.client.RestTemplate - Response 200 OK
23:59:55.796 [qtp1223357487-28] DEBUG org.springframework.web.client.RestTemplate - Reading to [org.springframework.security.oauth2.core.endpoint.OAuth2AccessTokenResponse] as "application/json;charset=UTF-8"
23:59:56.197 [qtp1223357487-28] DEBUG org.springframework.web.client.RestTemplate - HTTP GET https://**.oktapreview.com/oauth2/default/v1/keys
23:59:56.199 [qtp1223357487-28] DEBUG org.springframework.web.client.RestTemplate - Accept=[text/plain, application/json, application/*+json, */*]
23:59:57.063 [qtp1223357487-28] DEBUG org.springframework.web.client.RestTemplate - Response 200 OK
23:59:57.063 [qtp1223357487-28] DEBUG org.springframework.web.client.RestTemplate - Reading to [java.lang.String] as "application/json;charset=UTF-8"
23:59:57.091 [qtp1223357487-28] DEBUG org.springframework.security.authentication.DefaultAuthenticationEventPublisher - No event was found for the exception org.springframework.security.oauth2.core.OAuth2AuthenticationException
23:59:57.091 [qtp1223357487-28] DEBUG org.springframework.security.oauth2.client.web.OAuth2LoginAuthenticationFilter - Authentication request failed: org.springframework.security.oauth2.core.OAuth2AuthenticationException: [invalid_id_token] An error occurred while attempting to decode the Jwt: The ID Token contains invalid claims: {iat=2020-03-18T18:31:58Z}
org.springframework.security.oauth2.core.OAuth2AuthenticationException: [invalid_id_token] An error occurred while attempting to decode the Jwt: The ID Token contains invalid claims: {iat=2020-03-18T18:31:58Z}
at org.springframework.security.oauth2.client.oidc.authentication.OidcAuthorizationCodeAuthenticationProvider.createOidcToken(OidcAuthorizationCodeAuthenticationProvider.java:232)
at org.springframework.security.oauth2.client.oidc.authentication.OidcAuthorizationCodeAuthenticationProvider.authenticate(OidcAuthorizationCodeAuthenticationProvider.java:161)
at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:175)
a.......
at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.security.oauth2.jwt.JwtValidationException: An error occurred while attempting to decode the Jwt: The ID Token contains invalid claims: {iat=2020-03-18T18:31:58Z}
at org.springframework.security.oauth2.jwt.NimbusJwtDecoder.validateJwt(NimbusJwtDecoder.java:170)
at org.springframework.security.oauth2.jwt.NimbusJwtDecoder.decode(NimbusJwtDecoder.java:126)
at org.springframework.security.oauth2.client.oidc.authentication.OidcAuthorizationCodeAuthenticationProvider.createOidcToken(OidcAuthorizationCodeAuthenticationProvider.java:229)
... 58 common frames omitted
```

After doing lot of research we indentified okta is not working with latest Okta spring boot starter versions(i.e 1.2.0,1.3.0,1.4.0,1.2.1,1.1.0)
It's working only with below versions whereas earlier it's worked with all Okta spring boot starter dependcies.
SpringBoot version 2.1.4  and Okta spring boot starter 0.6.0.

Success reference log:
```txt
Redirecting to 'https://dev-*****.okta.com/oauth2/default/v1/authorize?client_id=0oa42cj66nCz42kCO4x6&redirect_uri=http://localhost:9090/login&response_type=code&scope=profile%20email%20openid&state=JSQu0q'
Recived [GET /login?code=VpDHXdJdWEifZ5HUCp01&state=JSQu0q HTTP/1.1
Start processing with input [code=VpDHXdJdWEifZ5HUCp01&state=JSQu0q]
Retrieving token from https://dev-*****.okta.com/oauth2/default/v1/token
HTTP POST https://dev-*****.okta.com/oauth2/default/v1/token
Encoding and sending form: {grant_type=[authorization_code], code=[VpDHXdJdWEifZ5HUCp01], redirect_uri=[http://localhost:9090/login], client_id=[0oa42cj66nCz42kCO4x6], client_secret=[Hhsg4TFcXYVfzG_43I9Qclbe3hVaLQA7VLkuxKAY]}
pairs: {GET /oauth2/default/v1/keys HTTP/1.1: null}{User-Agent: Java/1.8.0_241}{Host: dev-*****.okta.com}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
pairs: {null: HTTP/1.1 200 OK}{Date: Wed, 18 Mar 2020 18:32:05 GMT}{Content-Type: application/json;charset=UTF-8}{Transfer-Encoding: chunked}{Connection: keep-alive}{Server: nginx}{Public-Key-Pins-Report-Only: pin-sha256="r5EfzZxQVvQpKo3AgYRaT7X2bDO/kj3ACwmxfdT2zt8="; pin-sha256="MaqlcUgk2mvY/RFSGeSwBRkI+rZ6/dxe/DuQfBT/vnQ="; pin-sha256="72G5IEvDEWn+EThf3qjR7/bQSWaS2ZSLqolhnO6iyJI="; pin-sha256="rrV6CLCCvqnk89gWibYT0JO6fNQ8cCit7GGoiVTjCOg="; max-age=60; report-uri="https://okta.report-uri.io/r/default/hpkp/reportOnly"}{X-Okta-Request-Id: XnJpJRtULtiOXRqDmcTT9QAACB4}{X-XSS-Protection: 1; mode=block; report=https://okta.report-uri.com/r/d/xss/enforce}{P3P: CP="HONK"}{X-Rate-Limit-Limit: 3000}{X-Rate-Limit-Remaining: 2999}{X-Rate-Limit-Reset: 1584556385}{Content-Security-Policy-Report-Only: default-src 'self' *.oktacdn.com dev-*****.okta.com; connect-src 'self' *.oktacdn.com *.mixpanel.com *.mapbox.com app.pendo.io data.pendo.io pendo-static-5634101834153984.storage.googleapis.com dev-*****.okta.com dev-*****-admin.okta.com https://oinmanager.okta.com data:; script-src 'unsafe-inline' 'unsafe-eval' 'self' *.oktacdn.com; style-src 'unsafe-inline' 'self' *.oktacdn.com app.pendo.io cdn.pendo.io pendo-static-5634101834153984.storage.googleapis.com; frame-src 'self' login.okta.com dev-*****.okta.com dev-*****-admin.okta.com; img-src 'self' *.oktacdn.com dev-*****.okta.com *.tiles.mapbox.com *.mapbox.com app.pendo.io data.pendo.io cdn.pendo.io pendo-static-5634101834153984.storage.googleapis.com data: blob:; font-src data: 'self' *.oktacdn.com fonts.gstatic.com; report-uri https://okta.report-uri.com/r/d/csp/reportOnly; report-to csp-report}{Report-To: {"group":"csp-report","max_age":31536000,"endpoints":[{"url":"https://okta.report-uri.com/r/d/csp/reportOnly"}],"include_subdomains":true}}{Cache-Control: max-age=3845888, must-revalidate}{Expires: Sat, 02 May 2020 06:50:13 GMT}{X-Content-Type-Options: nosniff}{Strict-Transport-Security: max-age=315360000}{X-Robots-Tag: none}{Set-Cookie: sid=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/}{Set-Cookie: JSESSIONID=FFC9AE6B3EDB563CBC19AFD92043C090; Path=/; Secure; HttpOnly}
:AuditEvent [timestamp=2020-03-18T18:30:03.340Z, principal=smamidi@*****.com, type=AUTHENTICATION_SUCCESS, data={details=remoteAddress=0:0:0:0:0:0:0:1, sessionId=<SESSION>, tokenType=BearertokenValue=<TOKEN>}]
Principal: smamidi@*****.com; Credentials: [PROTECTED]; Authenticated: true; Details: remoteAddress=0:0:0:0:0:0:0:1, sessionId=<SESSION>, tokenType=BearertokenValue=<TOKEN>; Not granted any authorities
Redirecting to DefaultSavedRequest Url: http://localhost:9090/
Redirecting to 'http://localhost:9090/'
```

Note:
we indentified Spring /Springboot is not working with latest Okta spring boot starter versions(i.e 1.2.0,1.3.0,1.4.0,1.2.1,1.1.0)

One observation is that is  While sending a HTTP POST Request https://**.oktapreview.com/oauth2/default/v1/token
The following parameters is not sent with the request 
client_id and client_secret parameters are not sent
please see the below request.
Writing [{grant_type=[authorization_code], code=[wzOVlKFV6bLvOdi2P54f], redirect_uri=[http://localhost:4321/login/oauth2/code/okta]}] as "application/x-www-form-urlencoded;charset=UTF-8"

But Okta spring boot starter 0.6.0.The following parameters is sent with the request 
client_id and client_secret parameters are sent in the request.
HTTP POST https://dev-****.okta.com/oauth2/default/v1/token
Encoding and sending form:` {grant_type=[authorization_code], code=[VpDHXdJdWEifZ5HUCp01], redirect_uri=[http://localhost:9090/login], client_id=[0oa42cj66nCz42kCO4x6], client_secret=[hidden_secret]}`

Could you please Fix the issue.

**Comment by bdemers** [comment]
An "Invalid claims" error that references a date field is usually caused by a clock synchronization issue. Can you check your clock sync and try again?

Also, I would recommend using the latest Spring boot version too `2.2.5` and the latest Okta-Spring-Boot-Starter: `1.4.0`

The older versions of this project i.e. `0.6.0` (and older versions of Spring Boot/Security) used a different OAuth library, this library was since moved into Spring-Security itself.
(that library is now deprecated: https://github.com/spring-projects/spring-security-oauth)

Keep us posted!

**Comment by Rajasekharjava** [comment]
Yes Even we tried Latest springboot version 2.2.5 and okta springboot starter 1.4.0 
same issue is occurred. 
 clock synchronization issue. Can you check your clock sync and try again?
   We will not change any logic to integrate with okta right
As of my knowledge we need to add okta springboot starter dependency and add client id and client secret and issuer uri in the application.properties file 
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.5.RELEASE</version>
		<relativePath/> 
	</parent>
	<groupId>com.boot.okta</groupId>
	<artifactId>SpringBootWithOktaNew</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>SpringBootWithOktaNew</name>
	<description>SpringBootWithOktaNew</description>

	<properties>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>com.okta.spring</groupId>
			<artifactId>okta-spring-boot-starter</artifactId>
			<version>1.4.0</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>

**Comment by Rajasekharjava** [comment]
These are the three properties we need to add in application.properties 
okta.oauth2.client-id=******
okta.oauth2.client-secret=******
okta.oauth2.issuer=*******

**Comment by bdemers** [comment]
@Rajasekharjava the error you indicated:
```
The ID Token contains invalid claims: {iat=2020-03-18T18:31:58Z}
```
Is a JWT validation error, usually this indicates that the system clock on your server Is off.
`iat` - Issued At, my guess is your clock is behind this date.

Which NTP servers are you currently using?

**Comment by Rajasekharjava** [comment]
Yeah Got it @bdemers .Thank you

**Comment by Rajasekharjava** [comment]
Thank you @bdemers
