### ISSUE TITLE
Can We integrate Spring 5 with okta 

### ISSUE THREAD

**Issue by Rajasekharjava** [okta/okta-spring-boot#166]
We have a legacy spring application .As per client Request we need to integrate with okta.
Could you please suggest how we need to meet the requirement?

**Comment by bdemers** [comment]
It depends how “legacy” we are talking ;) 
Spring Security has had OAuth2 for a while now (though it’s much more complete in current versions).

One of the easiest options for legacy apps though is using Spring Gateway: https://developer.okta.com/blog/2020/01/08/secure-legacy-spring-cloud-gateway

Keep us posted!

**Comment by Rajasekharjava** [comment]
ok Thanks @bdemers
