### ISSUE TITLE
 How to log out okta session using spring secuirty

### ISSUE THREAD

**Issue by Rajasekharjava** [okta/okta-spring-boot#167]
I have tried so many directions to clear the okta session but it didn't .could you please suggest me how we can do that. if I call SecurityContextHolder.clearContext() method is just clearing the spring security session but okta sid and Jsession is not.
Could you please help me out on this.

**Comment by arvindkrishnakumar-okta** [comment]
@Rajasekharjava - You might want to take a look at https://developer.okta.com/blog/2020/03/27/spring-oidc-logout-options and see if it helps?

**Comment by Rajasekharjava** [comment]
We have gone through this blog previously.But We are using legacy spring application and also we are giving provision to indiavidual application login as well as okta login .In both cases we need to log out the both sessions.so thats why we are facing issue .if it is a one direct okta login option
above blog will be good enough to implement log out functionality .so any way thanks for help

**Comment by Rajasekharjava** [comment]
> @Rajasekharjava - You might want to take a look at https://developer.okta.com/blog/2020/03/27/spring-oidc-logout-options and see if it helps?

Thanks arvindkrishnakumar-okta

**Comment by bdemers** [comment]
@Rajasekharjava Logout is an OIDC specific feature, previous versions of Spring Security (<5) didn't have support for OIDC.
