### ISSUE TITLE
Any indication on the next release?

### ISSUE THREAD

**Issue by peavers** [okta/okta-spring-boot#17]
0.2.0 is looking very helpful for us moving forward - any idea when it will find it's way out to the wild?

**Comment by bdemers** [comment]
Not sure how I missed this one, but any day now.  We are code complete, just waiting on some formalities, grab the SNAPSHOT and try it out!

**Comment by peavers** [comment]
Nice work on the new 0.2.0 release :)

Loving the work you're all doing, keep it up _b

**Comment by bdemers** [comment]
Thanks!!
