### ISSUE TITLE
OIDC Properties static discovery not always correct

### ISSUE THREAD

**Issue by Stillglade** [okta/okta-spring-boot#171]
The `OktaOAuth2PropertiesMappingEnvironmentPostProcessor` assumes that the Okta endpoints can be derived from the issuer URL, but this hardcoded assumption is incorrect.  In my org, the Okta `https://<myorg>.oktapreview.com/.well-known/openid-configuration` contains this:

```
issuer: "https://<myorg>.oktapreview.com",
authorization_endpoint: "https://<myorg>.oktapreview.com/oauth2/v1/authorize",
token_endpoint: "https://<myorg>.oktapreview.com/oauth2/v1/token",
userinfo_endpoint: "https://<myorg>.oktapreview.com/oauth2/v1/userinfo",
registration_endpoint: "https://<myorg>.oktapreview.com/oauth2/v1/clients",
jwks_uri: "https://<myorg>.oktapreview.com/oauth2/v1/keys"
```

Notice how the issuer uri is at the root of the domain, whereas the other uris have a "/oauth2" prefix.

**Comment by bdemers** [comment]
Thanks @Stillglade!
Supporting the root org issuer is on the roadmap. Currently, you can either use a "Custom Authorization Server", for example, new Okta Developer accounts are provisioned with one named `default`.

You can also use Spring Security out of the box to support this type of issuer.  Just note, that the root org does NOT support JWT access tokens (this may not matter depending on what you are building)

cc: @arvindkrishnakumar-okta

**Comment by Stillglade** [comment]
I am attempting to setup an API as a resource server that takes in a JWT OIDC token established within an Angular app.  In our Org, we are using Active Directory with an agent.

**Comment by bdemers** [comment]
Ahh, I see, you have two options:

1.) Validate the token remotely (OAuth access tokens are opaque strings per the spec, it just happens that many shops use JWTs).  The root Org tokens cannot be validated locally as a JWT (even though the string is structured that way).  (Spring Security has support for `opaque` tokens)

2.) Create a "custom authorization server", and validate the JWT locally in your resource server.
I usually recommend this approach when possible.

If you don't have the ability to create a custom authorization server, signup for a free Developer account: https://developer.okta.com/signup and try it out.  
Then contact support and see about enabling it

**Comment by Stillglade** [comment]
I am attempting to validate remotely.  I added `spring-boot-starter-oauth2-resource-server` as a dependency and have configured my root issuer uri as the value for `spring.security.oauth2.resourceserver.jwt.issuer-uri`.  Interstingly, if I take the incoming Authorization header and use it to hit the `<myorg>.oktapreview.com/oauth2/v1/keys` or `<myorg>.oktapreview.com/oauth2/v1/userinfo` and I can see a nice 200 response, but when I hit my configured API, I just get 401s.  I'll keep playing with it while trying to push for a custom auth server.

**Comment by bdemers** [comment]
Spring Security doesn't print much in the logs by default (for good reason), but if you turn up the level it should help resolve your 401

**Comment by Stillglade** [comment]
In case someone else stumbles upon this, this was a very useful page for understanding the issue: https://support.okta.com/help/s/article/Signature-Validation-Failed-on-Access-Token

**Comment by hanswesterbeek** [comment]
I'm also hitting the issue mentioned in the OP.

Do I understand correctly that the `okta-spring-boot-starter` really only works with okta developer-envs and not with regular okta production/preview environments because it garbles the various urls published at `/.well-known/openid-configuration`?

Or is there some simple remedy I am missing? Because I also got my client to work just fine with my devaccount, only to hit this issue when to connect to my organizations actual okta-env.

**Comment by Stillglade** [comment]
It should work for any environment, just make sure you are using an Authorization Server within Okta and not just the root issuer uris.  In other words, the issuer uri you are using should look like: https://<organization>.<okta || oktapreview>.com/oauth2/<some-generated-auth-server-id>

**Comment by arvindkrishnakumar-okta** [comment]
@hanswesterbeek Thanks for posting!

What does your issuer/org URI look like?

**Comment by hanswesterbeek** [comment]
The issuer is the issuer that exists by default, eg. `https://{myorg}.oktapreview.com` or `https://{myorg}.okta.com`.

Shouldn't that be the one I use?

**Comment by Stillglade** [comment]
If you have a default Authorization Server, the URI would be `https://{myorg}.okta.com/oauth2/default` as opposed to the root URI that you reference.  The root org issuer which you reference will not work for now with this library.  You can get it to work using introspection (not with jwks) but you would need to directly configure Spring Security for that.

**Comment by hanswesterbeek** [comment]
I ended up not using this lib and setting all the spring-security props (such as `spring.security.oauth2.client.provider.okta.issuer-uri`) myself.

I think this lib should work out-of-the-box for the production root issuers.

**Comment by bdemers** [comment]
@hanswesterbeek agreed! We are working on it ;)

**Comment by arvindkrishnakumar-okta** [comment]
The latest release `v2.0.0` addresses this. Feel free to reopen the issue if there are any followups.
