### ISSUE TITLE
Update to Okta SDK v2

### ISSUE THREAD

**Issue by bdemers** [okta/okta-spring-boot#176]
This is an _indirect_ breaking change and will require a major version bump

**Comment by sorin-costea** [comment]
Any timeline for this? Thank you!

**Comment by arvindkrishnakumar-okta** [comment]
@sorin-costea Thanks for checking. It is definitely a priority item on our list of deliverables. Expect it to be released in the next week or so.

**Comment by smilani** [comment]
Do we have now a timeline ? It's now 2 weeks already since the last comment.

**Comment by arvindkrishnakumar-okta** [comment]
@smilani Thanks for checking! We're on it, stay tuned!

**Comment by christiangoudreau** [comment]
I'm also really eager to see that coming!

**Comment by christiangoudreau** [comment]
It is now version 3.0.1... When can we hope to have the latest version?

Thanks
