### ISSUE TITLE
Should I use OidcUser or Principal?

### ISSUE THREAD

**Issue by jhullse** [okta/okta-spring-boot#181]
Hi everyone,

I'm implementing a SPA that authenticates the user using Okta Authorization Code flow. Everything works fine and I get the access token by the end.

In the API side I'm using okta-spring-boot (**version 1.4.0**) to verify the token and allow the user to use the resource server with the token received before. I followed the [Supporting client side applications - OAuth Implicit flow](https://github.com/okta/okta-spring-boot#supporting-client-side-applications---oauth-implicit-flow) guide in the README.md and also checked the [webflux-resource-server example](https://github.com/okta/okta-spring-boot/tree/master/examples/webflux-resource-server).

The README tells us to use **OidcUser** but for some reason I'm receiving **null** when injecting the user. If I change to **Principal** it works properly, the user is injected.

Is this the expected behavior?

**Comment by arvindkrishnakumar-okta** [comment]
@jhullse Thanks for your question!

Are you using your own custom Authorization/resource server? Can you share the server side configuration?

Ideally you should be able to inject `OidcUser` if your `oauth2Login()` client is configured with an OIDC provider.

**Comment by jhullse** [comment]
@arvindkrishnakumar-okta The configuration looks the same as the [Supporting client side applications - OAuth Implicit flow](https://github.com/okta/okta-spring-boot#supporting-client-side-applications---oauth-implicit-flow) guide. There is no custom authorization server, the API is only a resource server that verifies the token in order to allow or deny user access.

```java
@EnableWebFluxSecurity
@EnableReactiveMethodSecurity
public class WebFluxSecurityConfiguration {

  @Bean
  public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
    http
        .authorizeExchange()
            .anyExchange().authenticated()
            .and()
        .oauth2ResourceServer()
            .jwt();

    Okta.configureResourceServer401ResponseBody(http);

    return http.build();
  }
}
```

**Comment by arvindkrishnakumar-okta** [comment]
@jhullse Thanks for the response!

You might want to take a look at a similar question that is already answered at https://devforum.okta.com/t/authenticationprincipal-is-null-only-with-postman-request/8850/2.

**Comment by bdemers** [comment]
@jhullse 

If your API is only accessed as a resource server you could inject a `JwtAuthenticationToken` for example:

https://github.com/okta/samples-java-spring/blob/master/resource-server/src/main/java/com/okta/spring/example/ResourceServerExampleApplication.java#L53

(Depending on the type of information you want)

**Comment by jhullse** [comment]
In that case it seems OidcUser won't be available the way it is configured.

I'll try to use the alternatives you provided.

Thank you all.
