### ISSUE TITLE
Quickstart link is confusing

### ISSUE THREAD

**Issue by mraible** [okta/okta-spring-boot#186]
The second sentence of this repo's README says:

> Jump to our [quickstart](https://developer.okta.com/quickstart/#/angular/java/spring) to see how to configure various clients or follow along below to use curl.

The quickstart link takes you to a docs page that shows you how to get started with Angular. Also, there's no mention of curl, except for testing.

It might be better to show a quickstart, rather than to link to one. For example:

```
# install SDKMAN
curl -s "https://get.sdkman.io" | bash
# install JDK
sdk install java
# create Spring Boot app
curl https://start.spring.io/starter.zip -d dependencies=web,okta -d javaVersion=11 -o demo.zip
# unzip, then configure it with Okta's CLI
cd demo && okta apps create
# run it!
./mvnw spring-boot:run
```

**Comment by bdemers** [comment]
+1,
That doc page changed, it previously selected an angular front end and a Java backend. And we never updated the README.

💯 for your suggestion!!

**Comment by arvindkrishnakumar-okta** [comment]
Fixed.
