### ISSUE TITLE
Okta custom domain not working

### ISSUE THREAD

**Issue by RobMaskell** [okta/okta-spring-boot#187]
I had my app working with the okta dev domain but as I wanted to customise the login pages I need to make it work with a custom domain so I set that up and I'm getting the following error
```
Caused by: java.lang.IllegalStateException: The Issuer "https://dev-XXXXX.okta.com/oauth2/default" provided in the configuration metadata did not match the requested issuer "https://auth.shimoturin.site/oauth2/default"
```
I'tried to load the `.well-known` info and it only lists my custom domain so I'm stuck

**Comment by bretterer** [comment]
@RobMaskell Based on that error you showed, it seems that after updating to custom domain, you need to also change your configuration to reflect the new custom domain.

Do you have anywhere in your configuration `dev-XXXXXX.okta.com` still?  If you update your configuration with `auth.shimoturin.site` anywhere you still have `dev-XXXXXX-okta.com` does this resolve your error?

**Comment by bdemers** [comment]
In your Okta Developer Console, click on the menu **API** -> **Authorization Servers**
(if using the "Classic UI" its **Security** -> **API**)

Then edit your Authorization server, on the **Settings** tab, change the **Issuer** dropdown to your custom domain
This will change the OIDC discovery metadata and the issuer listed in any generated tokens to be your custom domain. 

Let me know if that helps!

**Comment by RobMaskell** [comment]
Yup it was the Security -> API setting. Thanks for that. I'd found the OIDC token config on the Application and thought I'd found them all :(

**Comment by bdemers** [comment]
Thanks for the follow up @RobMaskell! Glad we could help!
