### ISSUE TITLE
Update "What you need section" in README

### ISSUE THREAD

**Issue by mraible** [okta/okta-spring-boot#197]
Currently has:

* An Okta account (sign up for a [forever-free developer account](https://developer.okta.com/signup/))
* An OIDC application (typically a 'SPA' application)
* An [access token](https://developer.okta.com/docs/api/resources/oauth2.html)

Bullet #2 should say a "Web" app, not SPA. The access token link redirects to https://developer.okta.com/docs/reference/api/oidc/, which doesn't really say much about access tokens.

**Comment by robertjd** [comment]
PR is open for the typo (#199)

For the access token link, i guess this is mean to be a clue that you need an access token for this part of the guide:

If so, it seems we should have an easy way for someone to get that access token.  Basically walking through the enduser `/authorize` flow.  I took a look and I don't think we have [a guide](https://developer.okta.com/docs/guides/) for this (@jakubvul to sanity check. So it seems that we need to write a guide, or maybe consider this as something that `okta cli` could do?

**Comment by robertjd** [comment]
The guide I was looking for is here: https://developer.okta.com/docs/guides/implement-implicit/use-flow/

So it seems like we should link to that for now
