### ISSUE TITLE
After deploying to AWS /Azure the resource url doesn't work

### ISSUE THREAD

**Issue by shar-kumar** [okta/okta-spring-boot#200]
Downloaded source code from Git for okta-spring-boot-deploy-master project and deployed successfully on to AWS BeanStalk and Azure. But the URL does not work on browser. Always throws 400 error. Anyhelp is appreciated

**Comment by arvindkrishnakumar-okta** [comment]
@shar-kumar Can you tell us more? Which URL are you talking about and give us more details on the environment and steps to reproduce if possible?

**Comment by bdemers** [comment]
@shar-kumar We would need more details to help, you but without any context here are a few things to try:

1.) Always use HTTPS: https://developer.okta.com/docs/guides/deploy-your-app/java/#forcing-https
(this will make sure your redirect URIs are always correct, and you should always be using https anyway)

2.) Make sure you update your OIDC application's `redirectURIs` for your production deployment:
https://developer.okta.com/docs/guides/production-deployment/-/deployment-checklist/#application-settings

**Comment by shar-kumar** [comment]
hello @arvindkrishnakumar-okta and @bdemers thank you for responding!
I just downloaded source code from okta git repository and tried the example.
was able to deploy successfully to AWS cloud and Azure cloud. But when I try the uri on web page to run the application I was getting 400 error. In Okta login redirect  URI: https://<my-app-name>.azurewebsites.net/login/oauth2/code/okta and tried on browser with https://shar-app.azurewebsites.net/greeting
In azure it worked finally.
but in AWS I see again 400 error. I changed the login redirect URI in okta : as follows
http://<my-app-name>.eba-n7rwtncr.us-east-2.elasticbeanstalk.com//login/oauth2/code/okta
<img width="1091" alt="Screen Shot 2020-10-04 at 12 13 11 AM" src="https://user-images.githubusercontent.com/71625167/95006831-8821f880-05d6-11eb-88d1-3484cbd55a4e.png">

**Comment by bdemers** [comment]
@shar-kumar can you grab the URL of that Okta 400 page and paste it in this issue?

**Comment by shar-kumar** [comment]
https://dev-841535.okta.com/oauth2/default/v1/authorize?response_type=code&client_id=0oa12ux3icOIBhEYL4x7&scope=openid%20profile%20email%20address%20phone%20offline_access&state=qt3cqRJpWhxSnZDcoXiY2bY5ol8mnAW5pQzcBmk_r50%3D&redirect_uri=http://sharapp-env.eba-5wi28wgz.us-east-2.elasticbeanstalk.com/login/oauth2/code/okta&nonce=v7Ep7HfUVFsm3uNaGyFwFD-U-t0JxL4N9Im1smGG3ys

**Comment by bdemers** [comment]
Your system is reporting the following DNS URL: 
`http://sharapp-env.eba-5wi28wgz.us-east-2.elasticbeanstalk.com/login/oauth2/code/okta`

This would need to be your RedirectURI.  Once you have this working you will likely want to set up a constant DNS name, and HTTPS.

**Comment by shar-kumar** [comment]
Thank you! after trying so many times. Some how I used incorrect URI. Thank you so much once again!
problem is solved and now I can see the greetings webpage.
