### ISSUE TITLE
Add Okta Maven Plugin to generated pom.xml on start.spring.io

### ISSUE THREAD

**Issue by mraible** [okta/okta-spring-boot#205]
I don't know if it's possible, but it'd be cool if we could add the [Okta Maven Plugin](https://github.com/oktadeveloper/okta-maven-plugin) to the app's `pom.xml` when Okta is selected. Then, users could run easier-to-remember commands. For example:

```
mvn okta:register
mvn okta:spring-boot
```

**Comment by arvindkrishnakumar-okta** [comment]
Ack, will research.

**Comment by snicoll** [comment]
This should probably move to the [start.spring.io issue tracker](https://github.com/spring-io/start.spring.io/issues) with a code sample of what's required and we can take it from there.

**Comment by arvindkrishnakumar-okta** [comment]
@snicoll Thanks for the suggestion. That sounds reasonable.

**Comment by arvindkrishnakumar-okta** [comment]
Closing in favor of https://github.com/spring-io/start.spring.io/issues/568.
