### ISSUE TITLE
Okta Spring boot is getting port appended if application is running under firewall

### ISSUE THREAD

**Issue by niranjan-prusty** [okta/okta-spring-boot#245]
Hi,
I have a strange issue. I am not able to solve.
1. I have a Spring boot application running on Azure App Service. I used Okta Spring Starter - https://github.com/okta/okta-spring-boot. Application url is https://web.dev.mypepsico.com
2. Azure App Service is under ILB ASE. This is private VNet.
3. When traffic comes from internet (without VPN and PepsiCo Office network), goes through Pal Alto firewall. Port 15004 gets appended and https://web.dev.mypepsico.com:15004/oauth2/authorization/okta is not reachable.
4. Hitting https://web.dev.mypepsico.com within Office VPN OR office network, it does not go through firewall and Okta integration works fine.
5. The same application https://web.dev.mypepsico.com was integrated with PepsiCo SAML, it was working fine before adding Okta Spring code. After Okta spring code, somehow port is there in this url - https://web.dev.mypepsico.com:15004/oauth2/authorization/okta which obviously will not initiate authorization request.

I am attaching screenshot. I can send .har file with and without VPN, please email me.
[web.dev.mypepsiom_15004port.docx](https://github.com/okta/okta-spring-boot/files/5852573/web.dev.mypepsiom_15004port.docx)

**Comment by arvindkrishnakumar-okta** [comment]
@niranjan-prusty Are there any recent firewall rule/VPN changes in your organization in the context of this issue?

**Comment by niranjan-prusty** [comment]
Thanks for your response. No, there is no change in firewall. If I change
the application to saml, it works fine.

**Comment by arvindkrishnakumar-okta** [comment]
@niranjan-prusty You noted that it stopped working after adding Okta Spring code. Can you share more details on what exactly was added? What version of Okta spring boot are you using?

**Comment by niranjan-prusty** [comment]
@arvindkrishnakumar-okta   The below Okta Spring boot version added


		<dependency>
			<groupId>com.okta.spring</groupId>
			<artifactId>okta-spring-boot-starter</artifactId>
			<version>1.4.0</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-oauth2-client</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>

**Comment by niranjan-prusty** [comment]
There is Okta support ticket # 01027511as well. I had live session with semona.igama@okta.com yesterday. I sent her .har files.

**Comment by arvindkrishnakumar-okta** [comment]
Closing this in favor of the customer support ticket 01027511. Feel free to reopen if needed.
