### ISSUE TITLE
After okta login application redirection is not happening in springboot app deployed in weblogic server

### ISSUE THREAD

**Issue by smworld30** [okta/okta-spring-boot#260]
[stdout.log](https://github.com/okta/okta-spring-boot/files/6172227/stdout.log)

We have a springboot okta app deployed in weblogic 12c server.
When we hit the application link its redirecting to okta. After okta authentication its not redirecting back to application
giving below error . Detail error is attached.
Application URL : https://drswls1.corp.pep.pvt:54028/LoginPIWeb

Redirect URI in OKta we put like below:
https://drswls1.corp.pep.pvt:54028/LoginPIWeb/login/oauth2/code/okta

```txt
Forwarding to error page from request [/login/oauth2/code/okta] due to exception [com.nimbusds.jose.proc.JWSVerificationKeySelector.<init>(Ljava/util/Set;Lcom/nimbusds/jose/jwk/source/JWKSource;)V]

java.lang.NoSuchMethodError: com.nimbusds.jose.proc.JWSVerificationKeySelector.<init>(Ljava/util/Set;Lcom/nimbusds/jose/jwk/source/JWKSource;)V
	at org.springframework.security.oauth2.jwt.NimbusJwtDecoder$JwkSetUriJwtDecoderBuilder.jwsKeySelector(NimbusJwtDecoder.java:333) ~[spring-security-oauth2-jose-5.4.5.jar:5.4.5]
	at org.springframework.security.oauth2.jwt.NimbusJwtDecoder$JwkSetUriJwtDecoderBuilder.processor(NimbusJwtDecoder.java:348) ~[spring-security-oauth2-jose-5.4.5.jar:5.4.5]
	at org.springframework.security.oauth2.jwt.NimbusJwtDecoder$JwkSetUriJwtDecoderBuilder.build(NimbusJwtDecoder.java:361) ~[spring-security-oauth2-jose-5.4.5.jar:5.4.5]
	at org.springframework.security.oauth2.client.oidc.authentication.OidcIdTokenDecoderFactory.buildDecoder(OidcIdTokenDecoderFactory.java:167) ~[spring-security-oauth2-client-5.4.5.jar:5.4.5]
	at org.springframework.security.oauth2.client.oidc.authentication.OidcIdTokenDecoderFactory.lambda$createDecoder$3(OidcIdTokenDecoderFactory.java:129) ~[spring-security-oauth2-client-5.4.5.jar:5.4.5]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_261]
```

**Comment by arvindkrishnakumar-okta** [comment]
Which version of `nimbus-jose-jwt` is on your weblogic classpath?

**Comment by sergiishamrai-okta** [comment]
Thank you @smworld30 for your question.
Can you provide more details about your server configuration?
For me, it looks like some beans were not loaded properly by weblogic server.

**Comment by smworld30** [comment]
what type of configuration details you required? can you please classify? Do you want the source code to check? When I hit the application url  it is hitting okta. after giving the okta credentials it is redirecting this url not the actual application url

http://drswls1.corp.pep.pvt:54028/LoginPIWeb/login/oauth2/code/okta?code=QrEaRLkl5FWSyWNGfuU_HoTyVXAOGkUAiaGI36FKP_s&state=FDLup7oqwVZbh80gh182ZVKsF3AffxDb0JcGSmKldIk%3D

**Comment by bdemers** [comment]
This looks like a dependency version mismatch.

If you are using Maven you can run `mvn dependency:tree` or if you are using Gradle use, it should be something like `gradle dependencies`

You can remove any of your company deps from this list before attaching the result here.

**Comment by smworld30** [comment]
[dependency tree.txt](https://github.com/okta/okta-spring-boot/files/6172524/dependency.tree.txt)

Thanks for your reply. PFA

**Comment by bdemers** [comment]
The deps look fine at a quick glance. It looks like that missing constructor in`nimbus-jose-jwt` was added in version 8+
`com.nimbusds.jose.proc.JWSVerificationKeySelector.<init>(Ljava/util/Set;Lcom/nimbusds/jose/jwk/source/JWKSource;)`

From your dependency list, it looks like you _should_ have it, but... since you are deploying in a container (Weblogic). You may need to check your classpath to see where that class is getting loaded from.


A couple of suggestions on how you could track this down in your environment:
* Attach a debugger and check if that constructor exists
* While debugging, or add code that runs before your app starts that runs something like:

```java
System.out.println(
    com.nimbusds.jose.proc.JWSVerificationKeySelector.class.getProtectionDomain().getCodeSource().getLocation()
);
```

My guess is that Weblogic includes an older version of `nimbus-jose-jwt`, and that is leaking into your web application's classpath somehow.

Keep us posted!

**Comment by smworld30** [comment]
Thanks for your suggestion. I will check the version in weblogic and get back to you.

**Comment by smworld30** [comment]
yes thats weblogic classpath is updated. Thanks a lot for your suggestion.
