### ISSUE TITLE
When using an Org Authorization Server the Endpoint URLs are Incorrect

### ISSUE THREAD

**Issue by emanor-okta** [okta/okta-spring-boot#273]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests only.

### I'm submitting a
  - [X] bug report
  - [ ] feature request

### Background info

When using an Org Authorization Server as opposed to a custom Authorization Server the Endpoint URLs are built incorrectly. Using the latest Okta Hosted Sample with the below configurations,
```
OKTA_OAUTH2_ISSUER=https://{DOMAIN}.okta.com
OKTA_OAUTH2_CLIENT_ID=0oa1zj...
OKTA_OAUTH2_CLIENT_SECRET=ec9Ki3T66...
```
The /authorize URL will be built as `https://{DOMAIN}.okta.com/v1/authorize?response_type=... `
Should be `https://{DOMAIN}.okta.com/oauth2/v1/authorize?response_type=...` 

If I manually change the browser URL I will get redirected to my login. After login I will get 404 when okta-spring-boot tries to retrieve the /token endpoint. I assume the URL is built without 'oauth2' for this endpoint as well.

### Expected behavior

Endpoint URLs should be built with `/oauth2/v1/..` when using the Org Authorization server.

### What went wrong?

With the wrong URLs a 404 is received.

### Steps to reproduce

1. Clone latest [Okta Hosted Sample](https://github.com/okta/samples-java-spring/tree/master/okta-hosted-login)
2. Use latest okta-spring-boot
3. Set issuer to be the Org Authorization Server (https://{DOMAIN}.okta.com)
4. Start spring boot, navigate to localhost:8080
5. Click login

### SDK Version

2.0.1

**Comment by VitaliiTytarenko-okta** [comment]
@emanor-okta 
The authorization URI is obtained by adding `/v1/authorize` to your **_okta.oauth2.issuer_**.
I'm afraid, but `https://{DOMAIN}.okta.com` is not the correct format for the **_okta.oauth2.issuer_** property.
According to the [documentation](https://github.com/okta/okta-spring-boot/blob/0eecfa7fa71544fd3a19c88c87542a6d1390ced4/README.md#configure-your-properties), the issuer should look like: `https://{yourOktaDomain}/oauth2/default`. As a consequence of this the **_authorization-uri_** would be: `https://{yourOktaDomain}/oauth2/default/v1/authorize` and everything will work fine.

**Comment by arvindkrishnakumar-okta** [comment]
@VitaliiTytarenko-okta  `https://{yourOktaDomain}.okta.com` is a valid Issuer URL (See https://developer.okta.com/docs/concepts/auth-servers/#org-authorization-server).

**Comment by arvindkrishnakumar-okta** [comment]
Fix merged to master, will be published in next release.

**Comment by bml-axon** [comment]
Will this fix only go to the 2.x release branch?  We use Okta Spring Boot Starter 1.4.0 as we have Spring Boot 2.2 and we get the same problem with the URL being incorrect when using the Org Authorization Server.  I currently use a work-around by overriding the URLs in `security.oauth2.client.provider.okta.<*-uri>`.

**Comment by VitaliiTytarenko-okta** [comment]
I would recommend you upgrade.
It is very unlikely that we will make changes to an older version.
But let me see, maybe we can find a solution for you...

**Comment by bml-axon** [comment]
> I would recommend you upgrade.
> It is very unlikely that we will make changes to an older version.
> But let me see, maybe we can find a solution for you...

Thanks for the response Vitalii.  We're in the progress of upgrading but it takes time because of technical considerations.  We do have a work-around currently by overriding the correct URL in our Spring Security OAuth2 properties
