### ISSUE TITLE
Add support for Spring Boot 2.5

### ISSUE THREAD

**Issue by mraible** [okta/okta-spring-boot#280]
### I'm submitting a
  - [ ] bug report
  - [x] feature request

### Background info

If I try to create a Spring Boot app on [start.spring.io](https://start.spring.io), it says I can't use Okta.

<img width="1280" alt="Screen Shot 2021-05-03 at 3 07 16 PM" src="https://user-images.githubusercontent.com/17892/116934156-d0af9c00-ac21-11eb-815a-bf279491795f.png">

However, if I download Spring Boot 2.5 RC1 (with a "web" dependency), and modify the `DemoApplication.java` to match the following, everything works as expected.

```java
package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.oauth2.core.oidc.user.OidcUser;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

    @GetMapping("/")
    public String hello(@AuthenticationPrincipal OidcUser user) {
        return "Hello, " + user.getFullName();
    }
}
```

### Expected behavior

I should be able to create a Spring Boot 2.5 app on start.spring.io and include Okta.

### SDK Version

2.0.1

**Comment by aarongranick-okta** [comment]
Thanks for the report, @mraible. Looks like @bdemers is working on a PR to resolve this.
