### ISSUE TITLE
Okta Spring Boot under API Gateway

### ISSUE THREAD

**Issue by rsaestrela** [okta/okta-spring-boot#289]
Hi. Need some piece of advice on a Spring Boot service running on AWS under a load balancer (ELB) and API Gateway using Okta SB starter. Some operations are set up to make use of OIDC, but unfortunately is not possible to reach them because the authorization endpoint will be served with the load balancer host which is private. Calling any operation protected with OIDC will end with a 404 at `<load_balancer>/oauth2/authorization/okta`.

![diagram](https://i.ibb.co/fkQTn7m/spring-boot-okta.png "diagram")

Overriding `spring.security.oauth2.client.provider.okta.authorization-uri` won't work because API Gateway will redirect back to the load balancer and this will create a loop (ending with too many redirects).  I've tried the proxy solution too, but it doesn't seem to work for this use case. Only started having this issue after putting the gateway in front of the load balancer (and making it private). Any ideas? Thanks!

**Comment by bdemers** [comment]
Take a look at this doc: https://docs.spring.io/spring-boot/docs/2.0.1.RELEASE/reference/html/howto-security.html

(You probably need to set the x-forward-for props)

You will also need to use sticky sessions or use spring-session to cluster them.

Keep us posted!

**Comment by rsaestrela** [comment]
Solved. Setting the `server.forward-headers-strategy` to `FRAMEWORK` allows Spring to handle `x-forwarded-host` and `x-forwareded-prefix` (necessary in my use case) and the redirection happens to this host/prefix.
