### ISSUE TITLE
OktaOAuthCodeFlowConfiguration should also work with OAuth2SsoCustomConfiguration

### ISSUE THREAD

**Issue by westse** [okta/okta-spring-boot#29]
`OktaOAuthCodeFlowConfiguration` currently conditional on `OAuth2SsoDefaultConfiguration`, but should also allow `OAuth2SsoCustomConfiguration`.

**Comment by bdemers** [comment]
+1 we could possibly just use `@Conditional(EnableOAuth2SsoCondition.class)`

**Comment by bdemers** [comment]
doh, `EnableOAuth2SsoCondition` is package private.

@westse do you have an example I can use to write an IT around?
