### ISSUE TITLE
Okta Base/Org URL is NOT resolved from issuer property when using the Okta Org Issuer

### ISSUE THREAD

**Issue by bdemers** [okta/okta-spring-boot#36]
When using the Okta Org issuer `https://dev-123456.oktapreview.com/` the base url (used when the SDK is available) is not resolved.

This is because the current logic just strips `/oauth2/*` from the issuer and uses that.
We may want to set the base URL to the issuer,  if issuer URL does not contain `/oauth2/*`.

**Comment by ijer-web** [comment]
Me too

**Comment by arvindkrishnakumar-okta** [comment]
@bdemers With SDK `v2.0.0+` this should no longer be an issue. If the issuer does not contain `/oauth2/*`, we consider this as a root org issuer case and do the Opaque token flow.  This issue can therefore be closed.

**Comment by bdemers** [comment]
I think this issue was related to a mapping between the `okta.client.orgUrl` property and the `okta.oauth2.issuer` property that we did before the 1.0 release.  IIRC we no longer do that mapping and this issue could be closed
