### ISSUE TITLE
IntelliJ IDEA says clientId should be client-id and clientSecret should be client-secret

### ISSUE THREAD

**Issue by mraible** [okta/okta-spring-boot#37]
The bug is that if you use these values, no `clientId` is sent. If you use `clientId` and `clientSecret` it works. Screenshot of popup:

![image](https://user-images.githubusercontent.com/17892/35871729-38e2b70c-0b22-11e8-91e8-94ddf195e984.png)

**Comment by bdemers** [comment]
This should be fixed as of 1.0.
Spring Boot 2.0 made this much easier to deal with
