### ISSUE TITLE
RelaxedPropertyResolver removed from Spring Boot 2.x

### ISSUE THREAD

**Issue by lamba92** [okta/okta-spring-boot#39]
In [OktaSdkConfig.java class ](https://github.com/okta/okta-spring-boot/blob/master/sdk/src/main/java/com/okta/spring/sdk/OktaSdkConfig.java) you use RelaxedPropertyResolver, but it [has been removed from Spring Boot 2.x ](https://github.com/spring-projects/spring-boot/issues/9321)and won't be taken back. Please update the code.

**Comment by bdemers** [comment]
Will do Thanks!

**Comment by bdemers** [comment]
I don't have an estimate at the moment.  Ideally I'd like to support boot 1 and 2 on the same branch (which means supporting Spring Security 4 and 5 at the same time).  This might be possible, but there are a few things we need to look into

**Comment by Lamba92** [comment]
Well, then what do you recommend me to do right now, downgrade to 1.x?

**Comment by Lamba92** [comment]
Well, then what do you recommend me to do right now, downgrade to Spring 1.x?

**Comment by bdemers** [comment]
Yeah downgrade.  You could also use Spring Boot 2.x /w Spring Sec 5 directly (if you need to be on boot 2.x)

**Comment by bdemers** [comment]
Fixed in #58
