### ISSUE TITLE
Upgrading from 0.6.1 > 2.1.4 issues

### ISSUE THREAD

**Issue by vanhumbeecka** [okta/okta-spring-boot#393]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests only.

### I'm submitting a
  - [ x] bug report
  - [ ] feature request

### Background info
As part of package upgrade process, I stumbled upon seemingly unfixable issues related to Okta role claims.
In version `0.6.1` there is the option to add `rolesClaim` parameter, which adds this claim to returned tokens. This feature worked fine and roles where added to the returned token.

However, this changed apparently in `2.1.4` where this has been renamed to `groupsClaim` but this claim is now not being added anymore.
Since I don't have privilages to access the specific Okta Client itself, I can't change any current settings.

I'm not sure if this a bug or intentional behaviour to configure additional settings in the Okta client

### Expected behavior
I expect this to work without changing additional settings inside the Okta Client.

### What went wrong?
The roles (with `groupsClaim`) where not part of the tokens returned from Okta when upgrading to version `2.1.4`, even though `rolesClaim` was working in 0.6.1

**Comment by sergiishamrai-okta** [comment]
Hi @vanhumbeecka ,
Thanks for your question. The team will investigate this issue and get back to you soon.

**Comment by sergiishamrai-okta** [comment]
Internal ref: [OKTA-458885](https://oktainc.atlassian.net/browse/OKTA-458885)

**Comment by bdemers** [comment]
Hello @vanhumbeecka!

How are you setting the `okta.oauth2.groups-claim` property?  Is your `groups` claim set in both your ID tokens and Access Tokens? One of the big changes between the 0.x version and later versions is support for OIDC.

You can "preview" a token from your Okta Admin Console to verify this:
https://developer.okta.com/docs/guides/customize-tokens-returned-from-okta/main/

**Comment by vanhumbeecka** [comment]
I'm setting these values through the use of a `application.yml` file.
```yaml
okta:
  oauth2:
    issuer: https://{my-okta-host}/oauth2/{my-id}
    client-id:
    client-secret:
#    roles-claim: groups
    groups-claim: groups
```
Asside from upgrading the version of this library, I'm setting `groups-claim` instead of `roles-claim`, but now the `groups` key-value inside the access_token is not present anymore. Since we use this for authorization purposes on certain endpoints, these claims should go into the access_token for sure.
As I don't have access to the specific Okta settings (my org is restrictive) my hands are a bit tied here for the moment.

**Comment by bdemers** [comment]
Can you paste in the decoded versions of access tokens claims here? (please strip out any sensitive data, (similar to what you did in the above `application.yml` example.)

**Comment by vanhumbeecka** [comment]
Ok, I was able to get my custom `groups` inside my access token. Below is the obfuscated&decoded version on how it looks like.
However, the `@PreAuthorize("hasAuthority('staging-admin')")` decorators still blocks. So need to look further what's wrong.
```
{
  "ver": 1,
  "jti": "***",
  "iss": "https://***.okta.com/oauth2/***",
  "aud": "api://default",
  "iat": 1643814098,
  "exp": 1643817698,
  "cid": "00",
  "uid": "00",
  "scp": [
    "email",
    "profile",
    "openid"
  ],
  "sub": "a@example.com",
  "groups": [
    "staging-admin",
    "prod-admin"
  ]
}
```

**Comment by igloo12** [comment]
I having the same issue. When inspecting the `SecurityContextHolder.getContext().authentication` The items in the groups claim are missing from the authorities list

**Comment by arvindkrishnakumar-okta** [comment]
@igloo12 Would you mind checking out the latest release that uses Spring Boot 3.1.0 to see if this is still an issue?

**Comment by igloo12** [comment]
@arvindkrishnakumar-okta It is working in the new version thanks
