### ISSUE TITLE
Provide steps to run mvn install without failures

### ISSUE THREAD

**Issue by mraible** [okta/okta-spring-boot#42]
Since all the integration tests seem to fail, I'm guessing there's configuration that needs to happen before you can run `mvn install` w/o issues.

**Comment by bdemers** [comment]
+1, I updated the `okta/okta-sdk-java` wiki recently with instructions, but forgot to update this one too.

**Comment by bdemers** [comment]
@mraible an `mvn install` _should_ work now.  All of the OAuth interactions have been mocked out.
