### ISSUE TITLE
When threre exist other Environment instance, OktaOAuth2Configurer in okta-springboot-starter will cause NoUniqueBeanDefinitionException

### ISSUE THREAD

**Issue by fjdingsd** [okta/okta-spring-boot#445]
### Background info

When I have my own org.springframework.core.env.Environment instantce or exist in other third party dependency,  in the progress of  WebSecurityConfiguration.springSecurityFilterChain bean building ,OktaOAuth2Configurer in okta-springboot-starter initializes itself and to use **context.getBean(Environment.class))** will cause NoUniqueBeanDefinitionException

```java
final class OktaOAuth2Configurer extends AbstractHttpConfigurer<OktaOAuth2Configurer, HttpSecurity> {

    private static final Logger log = LoggerFactory.getLogger(OktaOAuth2Configurer.class);

    @SuppressWarnings("rawtypes")
    @Override
    public void init(HttpSecurity http) throws Exception {

        ApplicationContext context = http.getSharedObject(ApplicationContext.class);

        // make sure OktaOAuth2Properties are available
        if (!context.getBeansOfType(OktaOAuth2Properties.class).isEmpty()) {
            OktaOAuth2Properties oktaOAuth2Properties = context.getBean(OktaOAuth2Properties.class);

            // Auth Code Flow Config

            // if OAuth2ClientProperties bean is not available do NOT configure
            OAuth2ClientProperties.Provider propertiesProvider;
            OAuth2ClientProperties.Registration propertiesRegistration;
            if (!context.getBeansOfType(OAuth2ClientProperties.class).isEmpty()
                && (propertiesProvider = context.getBean(OAuth2ClientProperties.class).getProvider().get("okta")) != null
                && (propertiesRegistration = context.getBean(OAuth2ClientProperties.class).getRegistration().get("okta")) != null
                && !isEmpty(propertiesProvider.getIssuerUri())
                && !isEmpty(propertiesRegistration.getClientId())) {
                // configure Okta user services
                configureLogin(http, oktaOAuth2Properties, context.getBean(Environment.class));
```

and here's my own Environment definition:

```java
@Component("kmsEnvironment")
public class KMSEnvironment extends StandardEnvironment implements ConfigurableEnvironment , EnvironmentAware{
  // ... something else
}
```

and error log (kmsEnvironment is my own Environment definition):
```java
***************************
APPLICATION FAILED TO START
***************************

Description:

Method springSecurityFilterChain in org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration required a single bean, but 2 were found:
	- kmsEnvironment: defined in file KMSEncryptedEnvironment.class]
	- environment: a programmatically registered singleton

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

The root cause is OktaOAuth2Configurer use context.getBean and through only type as parameter. I think if OKTA want to introduce the Spring environment, it will be better to implement EnvironmentAware to set a Environment field and maybe farout to use context.getBean straightly.

### SDK Version
**okta-spring-boot-starter:2.1.5**

**Comment by arvindkrishnakumar-okta** [comment]
@fjdingsd Thanks for posting!

I'd like to learn more on why would you need to override the `org.springframework.core.env.Environment` yourself. Are you trying to isolate your env from Okta's env override just to add a set of your own environment variables?

**Comment by fjdingsd** [comment]
Overriding the `org.springframework.core.env.Environment` looks more like as Environment wrapper to encrypt some system/environment parameter values with jasypt. But that is not the point, this situation probably may occur in other third party component dependency introduced with OKTA simultaneously after all.  

As my posting code, I do qualify my bean with a unique name and do acquire it with that name by @Resource annotation.  Having said that OktaOAuth2Configurer.init() method to call Spring's context.getBean() which only based on class type by the choice OKTA made but find two bean causes occurrence of this situation.

My suggestion is that you may change the over-straight retrieving way for Environment after configurer bean has been created  like I said before and move retrieving to configurer creating phrase where more suitable for bean post process in 
processing Aware phrase to introduce original Spring Environment bean. At any rate, I appreciate it what the result is.
Thx !

**Comment by arvindkrishnakumar-okta** [comment]
@fjdingsd Thanks for the clarification!

We welcome and appreciate PR, if you'd like to contribute.
