### ISSUE TITLE
Provide example of injecting SDK

### ISSUE THREAD

**Issue by nbarbettini** [okta/okta-spring-boot#51]
The readme says:

> All that is left is to inject the client (com.okta.sdk.client.Client)!

Can we add an example for n00bs like me who don't know how? 😄

**Comment by mraible** [comment]
In case you're looking for something quick: https://github.com/oktadeveloper/okta-ionic-crypto-java-sdk-example/blob/master/holdings-api/src/main/java/com/okta/developer/holdingsapi/HoldingsController.java#L24

**Comment by bdemers** [comment]
@mraible's example is good, but that doesn't translate well to doc (as the using the injected value is identical to using it as a POJO)

Maybe we need to add more description around this? Ideas?
