### ISSUE TITLE
How to disable Okta Login when running locally?

### ISSUE THREAD

**Issue by cm1337** [okta/okta-spring-boot#524]
Hello. I am running version 1.4.0 of okta-spring-boot-starter.

I would like to have Okta login disabled when running locally, but enabled when running in other environments.

I have the whole login flow working just fine right now in all environments by setting the standard properties in my application.properties file and setting my SpringSecurityConfig list this

```
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests().antMatchers("/v1/healthcheck")
                .permitAll().requestMatchers(PathRequest.toStaticResources().atCommonLocations()).permitAll()
                .anyRequest().authenticated()
                .and().logout().logoutSuccessUrl("/")
                .and().logout().logoutSuccessHandler(oidcLogoutSuccessHandler())
                .and().oauth2Client()
                .and().oauth2Login().successHandler(successHandler());

        http.cors();
        http.csrf().disable();
    }
```

What is the easiest way to make it so that Okta Login is totally disabled locally?

Thank you!

**Comment by arvindkrishnakumar-okta** [comment]
Please take a look at a [this one](https://github.com/okta/okta-spring-boot/issues/106) to see if it helps!

**Comment by arvindkrishnakumar-okta** [comment]
Closing this, please reopen if necessary!
