### ISSUE TITLE
Returned redirect_uri includes http URL

### ISSUE THREAD

**Issue by tyokoi-folio** [okta/okta-spring-boot#53]
I'm now trying to implement oauth with okta using okta-spring-boot v0.3.0 with the following properties.

```
okta.oauth2.issuer=https://{domain}.okta.com
okta.oauth2.clientId=AAABBBCCC
okta.oauth2.clientSecret=AAABBBCCC
okta.oauth2.audience=api://default
okta.oauth2.redirect_uri=https://{domain}/authorization-code/callback
security.oauth2.sso.loginPath=/authorization-code/callback
security.oauth2.client.clientAuthenticationScheme=header 
```

However, when I accessed to the URL of my application, I got the redirected URL including weird redirect_uri. It should be https://{domain}, but I got http://{domain} and encountered 400 error...

```
https://{domain}.okta.com/oauth2/v1/authorize?client_id=AAABBBCCC&redirect_uri=http://{domain}
``` 

Any ideas? If you can give me any advice, it's very helpful for me. I'm completely stuck..

**Comment by mraible** [comment]
The redirect URI you send to Okta is the one that it redirects back to after you've logged in. Are you sure you're sending an https URL? If so, then something is changing that to http. Okta doesn't make that change.

**Comment by tyokoi-folio** [comment]
@mraible Thanks for your response. As I wrote above,  I configured `okta.oauth2.redirect_uri=https://{domain}/authorization-code/callback` in the property file. 

When I access to `https://{domain}/authorization-code/callback`, then it returns the location header bellow.

```
https://{domain}.okta.com/oauth2/v1/authorize?client_id=AAABBBCCC&redirect_uri=http://{domain}
```

As you mentioned, I also believe Okta does not do anything. I'm a newbie of okta-spring-boot. 

```
okta.oauth2.issuer=https://{domain}.okta.com
okta.oauth2.clientId=AAABBBCCC
okta.oauth2.clientSecret=AAABBBCCC
okta.oauth2.audience=api://default
okta.oauth2.redirect_uri=https://{domain}/authorization-code/callback
security.oauth2.sso.loginPath=/authorization-code/callback
security.oauth2.client.clientAuthenticationScheme=header 
```

If you can check the properties above and tell me something wrong in them, it would be great.

**Comment by bdemers** [comment]
@tyokoi-folio how did you make out?

Please reopen this issue if needed

**Comment by nashley** [comment]
I'm also running into this issue.

Not specifying `okta.oauth2.redirect-uri` results in an `http://` URL, and specifying a full URL just ends up with it appended to the `baseUrl`.
For example:
- `okta.oauth2.redirect-uri: https://domain.com/oauth2/authorization/okta` results in `https://domain.com/oauth2/authorization/oktahttp://domain.com/oauth2/authorization/okta`
- Omitting it results in `http://domain.com/oauth2/authorization/okta`, which doesn't use `https`

It looks like [this line](https://github.com/okta/okta-spring-boot/blob/master/oauth2/src/main/java/com/okta/spring/boot/oauth/env/OktaOAuth2PropertiesMappingEnvironmentPostProcessor.java#L126) is to blame:
```java
private PropertySource oktaRedirectUriPropertySource(Environment environment) {
        Map<String, Object> properties = new HashMap<>();
        properties.put("spring.security.oauth2.client.registration.okta.redirect-uri", "{baseUrl}${okta.oauth2.redirect-uri}");
        return new ConditionalMapPropertySource("okta-redirect-uri-helper", properties, environment, "okta.oauth2.redirect-uri");
    }
```

How is `baseUrl` set? How can it be told to use `https`? Why is this not the default?

Thanks, and let me know if/how I can help debug this.

**Comment by bdemers** [comment]
Hey @nashley 
Spring Security uses the current request URL for the `baseUrl`
There are a few other parameters you can use as well, you can view the related code here:

https://github.com/spring-projects/spring-security/blob/7cfb17a8a39dbdd0819b64c2b95f10ac85d184af/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/server/DefaultServerOAuth2AuthorizationRequestResolver.java#L175-L207

You should also be able to set the Spring Security property `spring.security.oauth2.client.registration.okta.redirect-uri` directly.

Sounds like you might need to set your `X-Forwarded-*` headers? https://docs.spring.io/spring-boot/docs/1.5.21.RELEASE/reference/html/howto-embedded-servlet-containers.html#howto-use-tomcat-behind-a-proxy-server

**Comment by nashley** [comment]
Hey @bdemers 
Specifying `server.use-forward-headers: true` seems to have worked! Thank you so much!

Good to know that `{baseUrl}` is built into `spring-security`.
I'm always surprised by how hard it seems to be to find the relevant Spring documentation via Google. I'm glad you knew where to look! :slightly_smiling_face: 

I believe the reason this was occurring is that I was testing on deployments behind a proxy that provided `https`, so Spring had no idea that it was capable of TLS. I'm surprised that this flag isn't enabled by default (and that relative paths aren't used for the redirect so the browser could figure it out on its own), but I'm happy to have fixed this.

Thanks again!

**Comment by nashley** [comment]
With [the spring-boot `2.2` update](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes#deprecations-in-spring-boot-22), `server.forward-headers-strategy` now needs to be specified instead of `server.use-forward-headers`. To get the same behavior as `server.use-forward-headers=true` from before, use `server.forward-headers-strategy=native`.
