### ISSUE TITLE
okta-spring-boot + okta-spring-sdk

### ISSUE THREAD

**Issue by paulux84** [okta/okta-spring-boot#54]
Hi,
i would configure "roles-claim: groups" and "principal-claim: email" as OAuth2 properties and to do so i've added okta-spring-sdk as dependency in my maven project.
The problem with this dependency returned OAuth2Athentication.userAuthetication object(UsernamePasswordAuthenticationToken) contains different "details" element. Inside "Token Preview"(from okta dashboard) i get all informations, but in the client i can't get the full map, Why?
How can i continue to get userInfo with also "roles-claim: groups" and "principal-claim: email"?
 
Thanks

**Comment by paulux84** [comment]
@bdemers i need to use `roles-claim: groups` and `principal-claim: email` and i can't set this info without `okta-spring-sdk`.
The difference is the element returned...without 'okta-spring-sdk' the `(LinkedHashMap)details` contains all userInfo like for example default okta field "locale", but without i get only `"ver", "jti",  "iss",  "aud", "iat", "exp", "cid",  "uid","scp","sub"` and some other field...but no userInfo inside

Thanks

**Comment by bdemers** [comment]
@paulux84
Take a look at our samples: https://github.com/okta/samples-java-spring, these examples do not use the SDK, but do use the starter.  The `-login` examples will show you a table of the available key/values.  Does this help?

**Comment by paulux84** [comment]
@bdemers no...i already do this. 
My main problem is to create a role based access using okta group so i can use for example `@Secured("admin")` where 'admin' is an okta user-group. The only way that i know to do so is to use the `role-claims` spring configuration so i need `okta-spring-sdk`.
There is another way to map `OAuth2Athentication.authorities` to okta grops?

For `principal-claim` configuration my workaround is a different configuration of "Profile" mappings in okta dashboard

**Comment by paulux84** [comment]
@bdemers okta-spring-boot-starter

**Comment by paulux84** [comment]
Sure...
P.s. may the issue depend on Spring Boot 2 usage?

Il lun 23 apr 2018, 20:59 Brian Demers <notifications@github.com> ha
scritto:

**Comment by bdemers** [comment]
Likely, see: #30

The samples are still a great starting point though, please re-open this issue if you are still running into issues

**Comment by paulux84** [comment]
Sorry...the sense of the problem was afflicted by a wrong translation...i'll try to explain better:

I use the following dependencies
```
       <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security.oauth.boot</groupId>
            <artifactId>spring-security-oauth2-autoconfigure</artifactId>
        </dependency>
```
And all works great and the returned `OAuth2Athentication.userAuthetication.details` contains all userInfo.
But if i add `okta-spring-boot-starter` the returned `OAuth2Athentication.userAuthetication.details` not contains userInfo, but "ver", "jti", "iss", "aud", "iat", "exp", "cid", "uid","scp","sub"..

**Comment by paulux84** [comment]
i've reopened the issue here #55
