### ISSUE TITLE
okta-spring-boot-starter + spring-security-oauth2-autoconfigure (linked to #54)

### ISSUE THREAD

**Issue by paulux84** [okta/okta-spring-boot#55]
Hi,
in my project i use the following dependencies

       <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security.oauth.boot</groupId>
            <artifactId>spring-security-oauth2-autoconfigure</artifactId>
        </dependency>

And all works great and the returned OAuth2Athentication.userAuthetication.details contains all userInfo.
But if i add okta-spring-boot-starter the returned OAuth2Athentication.userAuthetication.details not contains userInfo, but "ver", "jti", "iss", "aud", "iat", "exp", "cid", "uid","scp","sub".

Thanks
p.s.  from okta dashboard trought "Token Preview" i get all informations, so...the okta configuration is correct.

**Comment by bdemers** [comment]
I think I understand your question.

By default the our plugin does client side validation, and you get the access token JWT's claims for the user detail (locally validating the JWT and saving a remote API call). If you set the property `okta.oauth2.localTokenValidation=false` then a remote call will be made to the user info endpoint.

**Comment by paulux84** [comment]
Ok, but in this way i do 2 remote call every time while the "userInfo" that i want are mapped inside token using claims

**Comment by paulux84** [comment]
Ok, but in this way i do 2 remote call every time while the "userInfo" that i want are mapped inside token using claims

**Comment by bdemers** [comment]
Yes, at the moment, the parsing of the groups claim only works when validating tokens locally.  I've opened #56 to track this.  Until this is implemented you would need to handle this logic directly in your code.
