### ISSUE TITLE
Create authorities from Auth0 permissions claim

### ISSUE THREAD

**Issue by jimmyjames** [okta/okta-spring-boot#557]
### I'm submitting a
  - [ ] bug report
  - [X] feature request

### Background info

[As discussed](https://github.com/okta/okta-spring-boot/pull/547#issuecomment-1454348784) in #547, Auth0 API tokens may include a `permissions` claim, which is an array of permissions granted. This is part of Auth0's [RBAC feature](https://auth0.com/docs/manage-users/access-control/rbac).

With the change in #547, it is not possible to make authorization decisions using the `permissions` claim, as no authorities are created from the permissions in the JWT.

### Expected behavior

I would expect to be able to manage authorization for a resource based on the token's permissions claim:

```java 
@GetMapping("/message-permission")
@PreAuthorize("hasAuthority('read:messages')")
public String messagePerm() {
        return "secret message for permission!";
}
```

### What went wrong?

Authorities are not created from the `permissions` claim, so no authority exists from which to make an authorization decision based on permissions.

### Steps to reproduce

1. Create an API in the Auth0 dashboard
2. In the Settings tab of the API, ensure the "Enable RBAC" and "Add permissions in the access token" toggles are turned on (click Save)
3. Go the Permissions tab of the API, and create a permission
4. In the "Machine to Machine Applications" tab, expand the API you created, and ensure the permission you created is checked (don't forget to click Update)
5. Use the "Test" tab to obtain a token, and verify that it has the permissions claim with the permission you created in it
6. Restrict access to a resource based on the value of the permission, as shown above

### SDK Version

Tested using the code in #547

**Comment by arvindkrishnakumar-okta** [comment]
@jimmyjames Thanks for posting!

I will have to triage this internally and get back to you.

**Comment by arvindkrishnakumar-okta** [comment]
@jimmyjames Presently, If your JWT has a permissions claim, it “does” get converted to a `SimpleGrantedAuthority` with a `SCOPE_` prefix added by Spring security (by default) (Ref: https://github.com/spring-projects/spring-security/blob/main/oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtGrantedAuthoritiesConverter.java#L46). We do have UT in the SDK that test this behavior - https://github.com/okta/okta-spring-boot/blob/master/oauth2/src/test/groovy/com/okta/spring/boot/oauth/OktaJwtAuthenticationConverterTest.groovy#L49-L69.

We seem aligned with Spring security standards on the `SCOPE_` prefix being applied to `permissions` claim while converting it to `SimpleGrantedAuthority`. So this seems to work as designed/expected.

Feel free to followup/reopen this issue if necessary.
