### ISSUE TITLE
Setting `okta.oauth2.localTokenValidation` causes the `groups` returned in user details to NOT be parsed into Spring Authorities

### ISSUE THREAD

**Issue by bdemers** [okta/okta-spring-boot#56]
Processing of groups to authorities should NOT be tied to `localTokenValidation`

**Comment by bdemers** [comment]
@paulux84 I cannot reproduce this locally, any chance you have an example that will help?

**Comment by paulux84** [comment]
I must create one, but...before that I would try what happens with new okta
release...

Il gio 31 mag 2018, 18:58 Brian Demers <notifications@github.com> ha
scritto:

**Comment by arvindkrishnakumar-okta** [comment]
@bdemers This issue does not seem to be relevant anymore?

**Comment by bdemers** [comment]
Agreed
