### ISSUE TITLE
Add doc example for setting HTTP proxy config

### ISSUE THREAD

**Issue by bdemers** [okta/okta-spring-boot#57]
This _should_ be the standard `http(s).proxy*` properties, but a quick manual test and a doc update would be great.

**Comment by arvindkrishnakumar-okta** [comment]
Internal Ref: OKTA-356200

**Comment by VitaliiTytarenko-okta** [comment]
**`http.proxyHost`** and **`http.proxyPort`** are standard properties for configuring proxy settings for URLConnection from _`java.net`_ package. User can define these parameters as system properties or command line arguments, if he wants to work with HTTP on core Java. And looks it like this (all these classes from _`java.net`_):
```
        System.setProperty("http.proxyHost", "127.0.0.1");
        System.setProperty("http.proxyPort", "7000");
        URLConnection con = new URL(RESOURCE_URL).openConnection();
```
it's the same as:
```
        Proxy webProxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("127.0.0.1", 7000));
        URLConnection con = new URL(RESOURCE_URL).openConnection(webProxy);
```
This has nothing to do with the Okta product and we should not add it to the readme.

Here #233 we add HttpProxy configuration to Spring RestTemplate. I think this should become more useful. We add **`okta.oauth2.proxyHost`** and **`okta.oauth2.proxyPort`** properties for it. And we should not use `http.proxy*` here or mix with our custom properties. They are different and serve for different purposes.

So, I think, we should close this issue and continue work on PR mentioned above.

**Comment by VitaliiTytarenko-okta** [comment]
Close this issue since the necessary changes were made in #233
