### ISSUE TITLE
How to resolve OKTA OIDC issue [access_denied] policy evaluation failed for this request please check the policy configurations

### ISSUE THREAD

**Issue by UgoTran** [okta/okta-spring-boot#602]
my project using:
- spring boot 2.7.15
- okta-spring-boot-starter 2.1.7

Using OIDC's config guide on okta-spring-boot-starter with config OIDC on dev account -> **work well**

The problem is: may partner send me **okta.oauth2.*** config not work with same base code 
1. Error pic:
![image](https://github.com/okta/okta-spring-boot/assets/44249146/d876b55f-606d-4983-85f0-17e8d6f4a28b)

2. Sign On Policy pic:
![image](https://github.com/okta/okta-spring-boot/assets/44249146/d6362dc2-0d1b-434b-b33a-1e36e781f421)

3. .well-known openid configuration
https://team-login-stg.bunnings.com.au/oauth2/default/.well-known/openid-configuration

Thanks for support!

**Comment by arvindkrishnakumar-okta** [comment]
@UgoTran Thanks for posting!

I am not sure if I follow your description of the problem: "The problem is: may partner send me okta.oauth2.* config not work with same base code".

Can you please elaborate a bit more?

**Comment by UgoTran** [comment]
@arvindkrishnakumar-okta Thanks for response me.
That issue is resolved.
I using artifact _spring-security-oauth2-client_.
