### ISSUE TITLE
Update start.spring.io to allow usage with Spring Boot 3.2.0

### ISSUE THREAD

**Issue by mraible** [okta/okta-spring-boot#619]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

If you try to select the Okta Spring Boot starter on start.spring.io, it doesn't work.

<img width="1242" alt="Screenshot 2023-11-27 at 4 59 26 AM" src="https://github.com/okta/okta-spring-boot/assets/17892/e9b776c1-f0e4-428d-a36a-473d3b32531a">

### Expected behavior

The Okta Spring Boot starter should be allowed with Spring Boot 3.2.0. 

I've confirmed v3.0.5 works with [okta-spring-boot-sample](https://github.com/okta-samples/okta-spring-boot-sample/) for both Okta and Auth0.

**Comment by arvindkrishnakumar-okta** [comment]
@mraible the precursor to this would be to upgrade the okta-spring-boot SDK to use 3.2 Spring Boot Starter version (although you noted it works).
