### ISSUE TITLE
More configuration like public endpoints, etc.

### ISSUE THREAD

**Issue by miguefl** [okta/okta-spring-boot#63]
Hi, I couldn't find any information about extra configuration of this library.

I have a ReactJS web application and some java microservices that expose an API.

#### Example:

**Public (no JWT needed)**
GET:`/resource1`
GET: `/resource1/{id}`

**Private (JWT needed)**
POST: `/resource1`
DELETE, PATCH, PUT: `/resource1/{id}`
GET, POST:`/resource2`
GET, DELETE, PATCH, PUT: `/resource2/{id}`

#### Example:

User `u1` has `notes` in a database, but he shouldn't edit, delete or create other user's notes. In this scenario, `roles` and `groups` don't apply. 

My solution: I persist the `uid` like note's information and it checks that the `uid` in jwt is valid for the resource that I want to modify

Thanks.

**Comment by bdemers** [comment]
Hey @miguefl !

One of our samples works similar to this.  The root `/` resource is unprotected, but all others are:

https://github.com/okta/samples-java-spring/blob/master/okta-hosted-login/src/main/java/com/okta/spring/example/CodeFlowExampleApplication.java#L59 

Does that help?

**Comment by miguefl** [comment]
Maybe, but I don't have a SSO web application. Sorry, I'm going to edit the opening post.
I have a React application, that uses okta js api. And I have some microservices to differents purposes.

But, maybe I can do it in the same way.

Thanks.

**Comment by bdemers** [comment]
A resource server would work the same way.
Take a look at the Spring Security documentation for more info: https://docs.spring.io/spring-security/site/docs/5.0.5.RELEASE/reference/htmlsingle/#jc-authorize-requests
