### ISSUE TITLE
Spring Boot 2.0: OAuth2Authentication.userAuthentication.details has different info with Okta Starter

### ISSUE THREAD

**Issue by mraible** [okta/okta-spring-boot#66]
If I use the Okta Spring Boot Starter (v0.5.0), the `Principal` is of type `OAuth2Authentication`, but it does not contain any user information in `userAuthentication.getDetails()`. It contains access token information instead.

<img width="2032" alt="okta-starter-details" src="https://user-images.githubusercontent.com/17892/41243502-8a1f590a-6d5f-11e8-9552-4196b04963c7.png">

If I change my app to use the Spring Security Starter instead (and adjust properties accordingly), `userAuthentication.getDetails()` contains user information.

<img width="2032" alt="spring-security-details" src="https://user-images.githubusercontent.com/17892/41243503-8a3df6e4-6d5f-11e8-9e39-8053db156a83.png">

I think Okta's starter should be adjusted so it matches the behavior that Spring Security has by default.

**Comment by arvindkrishnakumar-okta** [comment]
@mraible I think this issue is no longer relevant. Can you confirm if we can close this?

**Comment by mraible** [comment]
@arvindkrishnakumar-okta I'm not sure if it's still an issue, but I haven't run into anything like this recently, so I'll close it.
