### ISSUE TITLE
Okta spring boot starter not working when using JPA dependency on spring boot

### ISSUE THREAD

**Issue by MHarisMumtaz** [okta/okta-spring-boot#71]
I have below okta dependencies:
 ```
<dependency>
		    <groupId>com.okta.spring</groupId>
		    <artifactId>okta-spring-boot-starter</artifactId>
		    <version>0.5.0</version>
		</dependency>
		<dependency>
           <groupId>org.springframework.security.oauth.boot</groupId>
           <artifactId>spring-security-oauth2-autoconfigure</artifactId>
           <version>2.0.1.RELEASE</version>
       </dependency>
```
it was working when there is no jpa dependency but when I add below Jpa dependency it stopped working and gives an error

```
 <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
```

> Error creating bean with name 'org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfiguration': Unsatisfied dependency expressed through field 'tokenServices'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'resourceServerTokenServices' defined in class path resource [com/okta/spring/oauth/implicit/ResourceServerConfig$LocalTokenValidationConfig.class]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class com.okta.spring.oauth.implicit.Non500ErrorDefaultTokenServices: Common causes of this problem include using a final class or a non-visible class; nested exception is org.springframework.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null

**Comment by bdemers** [comment]
@MHarisMumtaz does just adding the dependency cause the issue? no config needed?
We will take a look!

**Comment by handyccc** [comment]
I noticed you can work around this by setting token validation to server side in the application.properties file:

okta.oauth2.localTokenValidation=false

**Comment by bdemers** [comment]
@handyccc @MHarisMumtaz do you both have dev-tools on the classpath ?
(we just fixed an issue where when both dev-tools and a jpa lib were on the classpath it would cause an app to fail to start)

**Comment by handyccc** [comment]
Yes, i did

**Comment by thomasmchen** [comment]
@bdemers Just wanted to follow up on this issue as I encountered it as well. Was there an official fix for it? I have been using the same work around @handyccc suggested above.

**Comment by sergeytrasko** [comment]
Also faced the reported issue and used proposed workaround.
However a question - what might be negative impact of such workaround?

**Comment by bdemers** [comment]
This should no longer be an issue with 1.0+. please leave a comment if you are still hitting this issue

**Comment by ramkrishs** [comment]
still an issue i am getting this error with 1.1.0

**Comment by bdemers** [comment]
@ramkrishs, can you include the stacktrace you are seeing with 1.1.0?
Do you have actuator on the classpath?
