### ISSUE TITLE
always getting null for java.security.Principal

### ISSUE THREAD

**Issue by smile18** [okta/okta-spring-boot#76]
I am trying to get user details from accessToken as explained in [here](https://github.com/okta/okta-spring-boot#supporting-client-side-applications---oauth-implicit-flow). But I am always getting null .

Here are my dependencies ...

        <dependency>
            <groupId>com.okta.spring</groupId>
            <artifactId>okta-spring-boot-starter</artifactId>
            <version>0.6.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.security.oauth</groupId>
            <artifactId>spring-security-oauth2</artifactId>
            <version>2.2.0.RELEASE</version>
        </dependency>

I have added the config properties ...

    okta:
        oauth2:
            issuer: https://XXXXX.oktapreview.com/oauth2/default
            clientId: XXXXX
        oauth:
            issuer: https://XXXXX.oktapreview.com/oauth2/default
            clientId: XXXX

I tried with valid accessToken and also with idToken for all I am getting null value. Please let me know if anything needs to be added or anything wrong and how to test?

**Comment by smile18** [comment]
the sample worked perfectly. Thanks.

**Comment by bdemers** [comment]
@smile18
Thanks for letting us know!  I've reopened the issue.  We'll go through the readme again and make sure the initial doc is easier to follow (and probably link to the other example)

Thanks again!
