### ISSUE TITLE
Is there a way to override uri?

### ISSUE THREAD

**Issue by mkrichevsky** [okta/okta-spring-boot#80]
Hi

I'm facing an issue, that my company's issuer url is not the same for all endpoints.
For example, configuration is located at `https://{company}.oktapreview.com/.well-known/openid-configuration`, but keys are located at `https://{company}.oktapreview.com/oauth2/v1/keys`.
However, the same issuer url is used to do all the requests. Is there a way to override this behaviour? I tried creating primary bean of `JwkTokenStore` with correct url, but for somereason it had no effect.

Thanks in advance

**Comment by mkrichevsky** [comment]
I guess I'll just use spring security with custom filter that will be validating requests? (I need only validation)

**Comment by bdemers** [comment]
@mkrichevsky give it a shot, and keep us posted! Feel free to reopen this if needed

**Comment by bdemers** [comment]
Thanks for following up !

**Comment by mkrichevsky** [comment]
I ended up extending `WebSecurityConfigurerAdapter` to configure my endpoints with custom filter  that extends `BasicAuthenticationFilter` to validate all incoming requests against okta.
