### ISSUE TITLE
Spring Boot JavaFx Client

### ISSUE THREAD

**Issue by gtnarg** [okta/okta-spring-boot#81]
My client application is a spring boot javafx app connecting to a spring boot server application.  Do you have an examples of integration of okta on the client side where being redirected to a web page wouldn't be part of the flow?

A redirect to a webpage embedded within a javafx webview could also work.

**Comment by nbarbettini** [comment]
Can you describe a little more about what your client app and server do? Is the client making API calls to the server? What is the reason for avoiding the redirect?

**Comment by gtnarg** [comment]
I'm trying to connect a java client app (swing or javafx) making api calls to a server app over http.  It appears that your client integrations don't cover java (at least documented).  I'm trying to understand how I would integrate okta into a java client app?  I'm interested in both swing and javafx.

**Comment by gtnarg** [comment]
Perhaps this is what I'm looking for?

https://github.com/okta/okta.github.io/issues/1830

**Comment by bdemers** [comment]
My guess is you probably want to make your server a resource server, and have the client send the access token for each request.

You should be able to authenticate by showing your users a [web view](https://docs.oracle.com/javafx/2/webview/jfxpub-webview.htm) though I don’t know how secure this embedded browser is.

That said we do not have a Java desktop example at this time (only server examples).  Any OAuth 2.0 or OIDC client you could find would work though.

**Comment by bdemers** [comment]
Let's move this to okta/okta.github.io#1830

**Comment by bdemers** [comment]
Matt just pointed me to this project as well: https://github.com/Microsoft/oauth2-useragent
Thanks: @mraible
