### ISSUE TITLE
Error on spring boot custom login using widget in jsp

### ISSUE THREAD

**Issue by dineshbade** [okta/okta-spring-boot#84]
I have been trying to implement custom login using jsp as my view but i got error saying 

> We found some errors. Please review the form and make corrections.

but I got success response form /api/v1/auth when i check my network.
also it work fine with thymeleaf view.

**Comment by bdemers** [comment]
Go with Thymeleaf 😛 
Kidding!  What does the rendered HTML look like for the JSP version and the Thymeleaf version.  My guess is there is a element missing or maybe the config is slightly different.  Can you include the JSP snippet too?

**Comment by bdemers** [comment]
What does the HTML render as?

**Comment by bdemers** [comment]
@dineshbade, If you are still running into this issue, feel free to comment and reopen!
