### ISSUE TITLE
OidcDiscoveryClient doesn't work behind a proxy

### ISSUE THREAD

**Issue by PaulStat** [okta/okta-spring-boot#93]
As per title. It creates it's own rest template and uses the issuerUri to create requests, but it doesn't check the application.yml to see if a okt.client.proxy is set.

Suggest the rest template has a request factory set with a configured http client which can have it's HttpProxy set if it's part of the configuration.

**Comment by bdemers** [comment]
As a work around you can disable discovery by using `okta.oauth2.discoveryDisabled`

**Comment by PaulStat** [comment]
Thanks I have done for now but it would be nice if this was an option.

**Comment by bdemers** [comment]
Agreed!

**Comment by bdemers** [comment]
Discovery has been removed in current version 1.0+ (as this plugin knows how to build the relative URLs based in the issuer)
