### ISSUE TITLE
Update to Spring Boot 2.1

### ISSUE THREAD

**Issue by bdemers** [okta/okta-spring-boot#96]
and Spring Security 5.1 on include OIDC support

I've taken a first a pass through this and hacked it up enough to get the TCK (with modifications to pass).

Notes:
* Spring OAuth config property names/structure has changed
* breaking changes
* official support via Spring Security/Spring Boot now, older oauth packages are deprecated
* Resource server support only supports local validation of JWT based access tokens (not opaque tokens currently)
* The new [Spring OAuth doc](https://docs.spring.io/spring-security/site/docs/5.1.1.RELEASE/reference/htmlsingle/#oauth2client) is pretty good.
* OAuth2/OIDC code flow _just work_ when packages and properties are present, but most users will need to customize the configuration (this integration will need to be aware of this)

Tasks:
- [ ] Make group token claim configurable
- [ ] Add tests for autoconfiguration cases
  - make sure okta oauth auto config doesn't trigger when properties are not present
- [ ] Think about a solution to make changing the redirect uri easier to set (i.e. `/authorize-code/callback`
- [ ] create release notes / migration guide
- [ ] Make OktaOAuth2ConfigProperties just wrap the official properties (so users can set properties via the standard props or the simplified Okta ones (i.e. `okta.oauth2.client-id`)

**Comment by dhudec** [comment]
@bdemers Can you provide any update on how this is going or when we can expect a release? We just tried to update to springboot 2.1 to support upgrading another dependency and found that it is not supported by Okta yet, so we were forced to downgrade again.

**Comment by bdemers** [comment]
Actually yeah, I just forgot to add link them, I have an open PR if you want to take a look #99
