### ISSUE TITLE
Can't obtain user info on Controller

### ISSUE THREAD

**Issue by Verric** [okta/okta-spring-boot#97]
Hi,
Was wondering how to obtain the Principal from a request from an SPA, I think I've followed the resource server tutorial fine. I've got a stack over flow question: https://stackoverflow.com/questions/52982123/can-not-retrieve-principal-from-spring-okta-cra-spa

I've got a demo repo at: https://github.com/Verric/carty-temp

Im not sure if this relates  to #95  #76.

Basic details
Spring boot 2.0.6

` implementation('com.okta.spring:okta-spring-boot-starter:0.6.1') {exclude group: 'org.slf4j' }`

	implementation('org.springframework.boot:spring-boot-starter-web')

	implementation('org.springframework.boot:spring-boot-starter-data-jpa')

    implementation('org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure:2.0.6.RELEASE')

	implementation('org.springframework.boot:spring-boot-starter-validation')`

Note I had to ignore logging in spring boot okta as it was claiming about having both log4j2 and logback on the class path :p

P.S The authentication works fine, only users logged in (via okta) can access the resource server, however I'm just not sure how to get who is making the request :/

Thanks in advance

**Comment by bdemers** [comment]
It works the same way it would work with Spring Security, you can inject a `Principal` or an `Authentication` (or from `SecurityContextHolder`)

Does that help?

**Comment by Verric** [comment]
Hi,
Unfortunately not, I can see the token coming fine and the `authenticated` field on Authentication is set to true, however I do not get an user details :(

![screen shot 2018-10-30 at 9 13 39 am](https://user-images.githubusercontent.com/7123404/47683682-6d91b880-dc24-11e8-9cac-45468c023691.png)

**Comment by bdemers** [comment]
What does `auth.getName()` return? 

Or have you tried something like this:
https://github.com/okta/samples-java-spring/blob/master/resource-server/src/main/java/com/okta/spring/example/ResourceServerExampleApplication.java#L62-L64

**Comment by Verric** [comment]
Wow that was quick  `auth.getName()` returns an empty string :(

If I place the OAuth2Authenitcation as a method param, then it comes in as null

![screen shot 2018-10-30 at 9 27 38 am](https://user-images.githubusercontent.com/7123404/47684204-273d5900-dc26-11e8-910e-248dda327f3d.png)

**Comment by bdemers** [comment]
What happens when you use a `Principal` as a method param?

**Comment by Verric** [comment]
Still comes in as null :(
![screen shot 2018-10-30 at 11 39 12 am](https://user-images.githubusercontent.com/7123404/47688233-768c8500-dc38-11e8-863a-6f87f58483c2.png)

**Comment by bdemers** [comment]
I'm not sure what is going on, can you give this example a shot: https://github.com/okta/samples-java-spring/tree/master/resource-server 

Does that work for you?
